Com 2299
sophiemoustard/compani-webapp pull request #1233
Opened 2021-09-06 15:15 UTC by CorentinMartinot

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : formation, coté vendor

- Périmetre roles : vendor admion

- Cas d'usage :  je peux ajouter un.e stagiaire depuis le repertoire apprenants. 
                            + mini refacto : mutualisation dans la mixin

2021-09-06 15:53 UTC, ulysseferreira reviewed
c'est normal que quand on ne sélectionne pas de structure à la création ça mette par défaut la structure de la personne qui a créé le compte ?

2021-09-06 16:16 UTC, CorentinMartinot commented
> c'est normal que quand on ne sélectionne pas de structure à la création ça mette par défaut la structure de la personne qui a créé le compte ?

Non ca ne l'est pas, merci ! je regarde ça

2021-09-07 09:13 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +  },
je trouverais ca logique de laisser les `created` dans chaque composant car ils n'ont rien en commun

2021-09-07 09:26 UTC, sophiemoustard requested changes

2021-09-07 09:26 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +    goToLearnerProfile (row) {
je pense qu'il faut le laisser dans chauqe composant egalement car 
- coté  vendeur tu veux aller sur la page `ni users learners info`
- cote client tu veux aller sur la page `ni courses learners info`

2021-09-07 09:26 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      <q-btn class="fixed fab-custom" no-caps rounded color="primary" icon="add" label="Ajouter une personne"
une indentation en trop

2021-09-07 10:43 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +  },
done

2021-09-07 10:43 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +    goToLearnerProfile (row) {
done

2021-09-07 10:43 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      <q-btn class="fixed fab-custom" no-caps rounded color="primary" icon="add" label="Ajouter une personne"
done

2021-09-07 12:52 UTC, ulysseferreira reviewed
<img width="436" alt="Capture d’écran 2021-09-07 à 14 51 58" src="https://user-images.githubusercontent.com/70574422/132347716-956106fa-8942-44e8-a9f1-83e20876f32e.png">

Le champ structure n'est pas marqué comme requis

2021-09-07 13:45 UTC, ulysseferreira approved these changes

2021-09-07 13:45 UTC, ulysseferreira commented on src/core/mixins/learnerDirectoryMixin.js
> +      return this.learnerList.filter(user => user.learner.noDiacriticsName.match(new RegExp(formattedString, 'i')));
saut de ligne

2021-09-07 13:45 UTC, ulysseferreira commented on src/core/mixins/learnerDirectoryMixin.js
> +      return payload;
idem

2021-09-07 14:50 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +      return this.learnerList.filter(user => user.learner.noDiacriticsName.match(new RegExp(formattedString, 'i')));
done

2021-09-07 14:50 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +      return payload;
done

2021-09-07 15:11 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +    resetAddLearnerForm () {
resetLearnerCreationModal plutot

2021-09-07 15:12 UTC, sophiemoustard commented on src/core/mixins/learnerDirectoryMixin.js
> +      return payload;
tu peux utiliser une ternaire dans ton return

2021-09-07 15:14 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      :company-options="companyOptions" />
ca tient sur 3 lignes

2021-09-07 15:37 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/users/learners/LearnersDirectory.vue
> +      :company-options="companyOptions" />
cone

2021-09-07 15:37 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +      return payload;
done

2021-09-07 15:37 UTC, CorentinMartinot commented on src/core/mixins/learnerDirectoryMixin.js
> +    resetAddLearnerForm () {
done

2021-09-07 15:59 UTC, sophiemoustard approved these changes

2021-09-07 15:59 UTC, merged