COM-2308 : remove link request
sophiemoustard/compani-webapp pull request #1237
Opened 2021-09-07 09:51 UTC by ulysseferreira

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : client

- Périmetre roles : coach/admin

- Cas d'usage : je peux supprimer les demandes de rattachement à ma structure

2021-09-07 12:35 UTC, CorentinMartinot commented on src/core/api/CompanyLinkRequests.js
> +    await alenviAxios.delete(`${process.env.API_HOSTNAME}/companylinkrequests/${userId}`);
Je vois pas de pb a envoyer le userId pour identifier et supprimer la demande de rattachement, mais je trouverai ca plus propre d'envoyer l'id du CompanyLinkRequest

2021-09-07 13:33 UTC, ulysseferreira commented on src/core/api/CompanyLinkRequests.js
> +    await alenviAxios.delete(`${process.env.API_HOSTNAME}/companylinkrequests/${userId}`);
done

2021-09-07 15:28 UTC, sophiemoustard requested changes

2021-09-07 15:28 UTC, sophiemoustard commented on src/core/api/CompanyLinkRequests.js
> +  async remove (_id) {
on n'emploie pas de _ normalement ici

2021-09-07 15:28 UTC, sophiemoustard commented on src/core/components/CompanyLinkRequestCell.vue
> +    user () {
est ce vraiment utiile ?

2021-09-07 15:28 UTC, sophiemoustard commented on src/core/components/CompanyLinkRequestCell.vue
> +      await CompanyLinkRequests.remove(this.request._id);
try / catch

2021-09-07 15:28 UTC, sophiemoustard commented on src/core/components/CompanyLinkRequestCell.vue
> +              <div style="font-size: 14px" class="text-copper-grey-500">${this.user.local.email}</div>
peux tu utilser une classe ? 
c'est plus dans nos standard et en plus tu pourrais mutualiser avec au dessus

2021-09-07 15:31 UTC, sophiemoustard commented
apres avoir supprimé la demande l'encadré est toujours la 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/24521863/132371816-e13c1d5a-9ba9-435a-ba1f-a27cb891dd76.png">

2021-09-07 16:11 UTC, ulysseferreira commented on src/core/api/CompanyLinkRequests.js
> +  async remove (_id) {
done

2021-09-07 16:13 UTC, ulysseferreira commented on src/core/components/CompanyLinkRequestCell.vue
> +    user () {
done

2021-09-07 16:14 UTC, ulysseferreira commented on src/core/components/CompanyLinkRequestCell.vue
> +      await CompanyLinkRequests.remove(this.request._id);
done

2021-09-07 16:17 UTC, ulysseferreira commented on src/core/components/CompanyLinkRequestCell.vue
> +              <div style="font-size: 14px" class="text-copper-grey-500">${this.user.local.email}</div>
je l'ai fait comme ça parce qu'avec une classe il ne le comprend pas, sans doute dû au fait que c'est une string plus que du "vrai" html

2021-09-07 16:28 UTC, ulysseferreira commented
> apres avoir supprimé la demande l'encadré est toujours la
> <img alt="image" width="1148" src="https://user-images.githubusercontent.com/24521863/132371816-e13c1d5a-9ba9-435a-ba1f-a27cb891dd76.png">

tu es à jour sur les branches, moi ça me retire bien la div, à moins que ça soit lié au navigateur

2021-09-08 08:34 UTC, sophiemoustard approved these changes

2021-09-08 08:34 UTC, merged