COM-2333 company filter
sophiemoustard/compani-webapp pull request #1260
Opened 2021-09-15 14:39 UTC by CorentinMartinot

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : admin

- Cas d'usage : je peux filter les questionnaires en fct de la structure du stagiaire qui a repondu

2021-09-15 15:20 UTC, sophiemoustard commented on src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> +          ...uniqBy(formatAndSortOptions(companies, 'name'), 'value'),
pourquoi as tu besoin du uniqby ?

2021-09-15 15:27 UTC, sophiemoustard requested changes

2021-09-15 15:27 UTC, sophiemoustard commented on src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> +      <ni-select :options="companyList" :value="selectedCompany" @input="updateSelectedCompany" class="select" />
je crois que la classe select ne sert a rien

2021-09-15 16:36 UTC, CorentinMartinot commented on src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> +      <ni-select :options="companyList" :value="selectedCompany" @input="updateSelectedCompany" class="select" />
done

2021-09-15 16:36 UTC, CorentinMartinot commented on src/modules/vendor/components/questionnaires/ProfileAnswers.vue
> +          ...uniqBy(formatAndSortOptions(companies, 'name'), 'value'),
done

2021-09-16 06:46 UTC, sophiemoustard approved these changes

2021-09-16 08:34 UTC, ulysseferreira commented on src/modules/vendor/components/questionnaires/ProfileAnswers.vue
>            ...uniqBy(formatAndSortIdentityOptions(trainers), 'value'),
je crois que tu peux retirer le uniqBy ici aussi

2021-09-16 12:36 UTC, ulysseferreira approved these changes

2021-09-16 12:36 UTC, merged