COM-2483 refacto sms icon, notify and banner
sophiemoustard/compani-webapp pull request #1360
Opened 2021-11-17 16:54 UTC by CorentinMartinot

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur

- Périmetre roles : rof

- Cas d'usage : refacto de la banniere au dessus du bouton pour envoyer les sms.

2021-11-17 17:58 UTC, ulysseferreira commented on src/core/components/courses/ProfileAdmin.vue
> +      if (this.course.archivedAt) return NotifyWarning('Impossible: la formation est archivée.');
il manque un espace avant :

2021-11-17 17:58 UTC, ulysseferreira commented on src/core/components/courses/ProfileAdmin.vue
> +      if (this.isFinished) return NotifyWarning('Impossible: la formation est terminée.');
idem

2021-11-18 08:11 UTC, CorentinMartinot commented on src/core/components/courses/ProfileAdmin.vue
> +      if (this.course.archivedAt) return NotifyWarning('Impossible: la formation est archivée.');
done

2021-11-18 08:11 UTC, CorentinMartinot commented on src/core/components/courses/ProfileAdmin.vue
> +      if (this.isFinished) return NotifyWarning('Impossible: la formation est terminée.');
done

2021-11-18 08:49 UTC, ulysseferreira approved these changes

2021-11-19 08:05 UTC, sophiemoustard requested changes

2021-11-19 08:05 UTC, sophiemoustard commented on src/core/components/courses/ProfileAdmin.vue
> +
dqans les autres PR vous etes partis sur la terminologie "Vous ne pouvez pas ajouter de stagiaire à une formation archivée.". que penses tu de garder la meme pour ces message d'erreur ?

2021-11-19 08:05 UTC, sophiemoustard commented on src/core/components/courses/ProfileAdmin.vue
> +      return this.followUpDisabled || this.allFuturSlotsAreNotPlanned || noPhoneNumber;
est ce qu'il ne faudrait pas mettre un warning egalement pour la condition `allFuturSlotsAreNotPlanned` ?

2021-11-19 09:23 UTC, CorentinMartinot commented on src/core/components/courses/ProfileAdmin.vue
> +      return this.followUpDisabled || this.allFuturSlotsAreNotPlanned || noPhoneNumber;
doen

2021-11-19 09:23 UTC, CorentinMartinot commented on src/core/components/courses/ProfileAdmin.vue
> +
done

2021-11-19 10:20 UTC, sophiemoustard approved these changes

2021-11-19 17:56 UTC, merged