COM-2495 - helper can see customer absences on his planning
sophiemoustard/compani-webapp pull request #1363
Opened 2021-11-19 13:26 UTC by manonpalin

- J'ai ajouté une variable d'environnement :
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile

### POUR TESTER LA PR
- Périmetre interface : client 

- Périmetre roles : Aidant

- Cas d'usage : Je vois l'absence du beneficiaire sur l'agenda

2021-11-19 16:11 UTC, KennyCallegari commented on src/modules/client/components/planning/Agenda.vue
> +          : 'cursor-pointer',
Je ne pense pas qu'on veuille un cursor-pointer car ça donne envie de cliquer sur l'absence et rien ne se passe 😄

2021-11-19 16:11 UTC, KennyCallegari commented on src/modules/client/components/planning/Agenda.vue
>                    <p class="event-number-label">{{ event.inConflictEvents.length }}</p>
pourquoi ce changement ?

2021-11-19 17:31 UTC, manonpalin commented on src/modules/client/components/planning/Agenda.vue
> +          : 'cursor-pointer',
Oui bien vu :)

2021-11-19 17:35 UTC, manonpalin commented on src/modules/client/components/planning/Agenda.vue
>                    <p class="event-number-label">{{ event.inConflictEvents.length }}</p>
Pcq dans le cas d'une absence `event.inConflictEvents.length` n'existe pas... J'ai rectifié en `event.inConflictEvents && event.inConflictEvents.length ...` c'est peut être plus clair, qu'en penses-tu?

2021-11-22 07:24 UTC, manonpalin commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +          .map(event => (event.inConflictEvents = this.getInConflictEvents(event)));
J'ai essayé mais apres avoir fait le map sur interventions, la concaténation se passe mal

2021-11-22 07:56 UTC, sophiemoustard requested changes

2021-11-22 07:56 UTC, sophiemoustard commented on src/modules/client/components/planning/Agenda.vue
> +      return ['', event.isCancelled ? 'event-cancelled' : `event-${event.type}`];
tu peux passer une ligne avant

2021-11-22 07:56 UTC, sophiemoustard commented on src/modules/client/components/planning/Agenda.vue
> +      if (event.type !== CUSTOMER_ABSENCE) {
que penses tu de raisonner par la positive ici et donc de commencer par le cas `event.type === CUSTOMER_ABSENCE` ?

2021-11-22 07:56 UTC, sophiemoustard commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +          .map(event => (event.inConflictEvents = this.getInConflictEvents(event)));
je trouve ca tres etrange que ton code fonctionne ici car `filter` et `map` renvoient des nouveaux tableaux et ne modifie pas le tableau d'origine

2021-11-22 07:56 UTC, sophiemoustard commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +          .map(event => (event.inConflictEvents = this.getInConflictEvents(event)));
en fait la manipulation que tu fais ici n'est pas tres clair : dans le map tu ne renvoies pas un nouvel objet mais tu modifie par reference chaque evenement `event` ce qui n'est pas tres intuitif.
d'habitude, on fait plutot un map comme suit : `.map(event => ({ ...event, inConflictEvents: this.getInConflictEvents(event) }))`

Egalement comme la methode `getInConflictEvents` utilise `this.events`, si on l'utilise tel quel en faisant comme suit 
```
this.events = interventions.concat(customerAbsences);.map(...);
```
alors `this.events` vaut `[]` au moment où on appelle getInConflictEvents donc la methode ne fonctionne pas bien

2021-11-22 07:56 UTC, sophiemoustard commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +          .map(event => (event.inConflictEvents = this.getInConflictEvents(event)));
tu peux du coup faire comme suit : 

```
this.events = Object.freeze(interventions
          .concat(absences.map(abs => ({ ...abs, type: CUSTOMER_ABSENCE })))
          .map(event => ({ ...event, inConflictEvents: this.getInConflictEvents(interventions, event) })));
```

modifier la methode `getInConflictEvents` en mettant en argument `interventions`

2021-11-22 11:32 UTC, manonpalin commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +          .map(event => (event.inConflictEvents = this.getInConflictEvents(event)));
Hmm oui en effet, il me semblait que `.filter()` modifiait le tableau d'origine mais tu as raison, ce n'est pas le cas !
Je rectifie

2021-11-22 14:29 UTC, cmolle commented on src/modules/client/components/planning/Agenda.vue
> +      if (event.type === CUSTOMER_ABSENCE) return ['', event.isCancelled ? 'event-cancelled' : `event-${event.type}`];
A quoi sert le '' ?

2021-11-22 14:29 UTC, cmolle commented on src/modules/client/components/planning/Agenda.vue
> +        this.isCustomerPlanning && event?.inConflictEvents?.length === 1
Il me semble qu'on n'utilise pas encore l'operateur `?.` pour l'instant en webapp. Il n'est pas utilisable sur internet explorer.

2021-11-22 14:54 UTC, manonpalin commented on src/modules/client/components/planning/Agenda.vue
> +        this.isCustomerPlanning && event?.inConflictEvents?.length === 1
Ca marche, je corrige

2021-11-22 14:57 UTC, sophiemoustard requested changes

2021-11-22 14:57 UTC, sophiemoustard commented on src/modules/client/pages/customers/CustomerAgenda.vue
> +      return interventions.filter(
ici tu peux mettre un `if (event.type === CUSTOMER_ABSENCE)` et comme ca `inConflictEvents` est defini tout le temps

2021-11-22 15:08 UTC, manonpalin commented on src/modules/client/components/planning/Agenda.vue
> +      if (event.type === CUSTOMER_ABSENCE) return ['', event.isCancelled ? 'event-cancelled' : `event-${event.type}`];
Bien vu,  a rien dans ce cas

2021-11-22 15:18 UTC, cmolle approved these changes

2021-11-22 15:25 UTC, cmolle commented on src/modules/client/components/planning/Agenda.vue
> +                <div v-if="isCustomerPlanning && event.inConflictEvents && event.inConflictEvents.length !== 1"
Il faudrait mettre > 1 enfait ici. car les absences n'ont aps de conflit, mais du coup il y a un 0 et on peut cliquer sur l'evenement

2021-11-22 15:42 UTC, cmolle commented on src/modules/client/components/planning/Agenda.vue
> +                <div v-if="isCustomerPlanning && event.inConflictEvents && event.inConflictEvents.length !== 1"
Il faudrait faire pareil dans `openConflictModal` la modale s'ouvre toujours

2021-11-22 15:47 UTC, manonpalin commented on src/modules/client/components/planning/Agenda.vue
> +                <div v-if="isCustomerPlanning && event.inConflictEvents && event.inConflictEvents.length !== 1"
oui pardon! J'ai rectifié

2021-11-22 16:26 UTC, cmolle approved these changes

2021-11-23 07:18 UTC, sophiemoustard approved these changes

2021-11-23 07:24 UTC, merged