Com 2552
sophiemoustard/compani-webapp pull request #1386
Opened 2021-12-09 11:15 UTC by manonpalin

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile -np

- Périmetre interface : client

- Périmetre roles : auxiliaire, admin, coach

- Cas d'usage : Je peux editer une absence beneficiaire.
- Pour tester: 
   - creer deux absences beneficiaires
   - editer la premiere sans être en conflit avec la deuxième --> l'absence est editee
   - editer la premiere en étant en conflit avec la deuxième  --> erreur
   - arrêter le beneficiaire a partir d'une date
   - editer une absence en mettant une date de debut postérieure a la date d'arrêt --> erreur

2021-12-10 10:51 UTC, ulysseferreira reviewed
sur la modale d'édition quand tu ouvre le calendrier de endDate, les dates avant la date de début sont grisées mais sur le calendrier de startDate les dates après la endDate ne le sont pas, c'est volontaire ?

-------

Sophie : je pense que c'est une bonne chose de ne bloquer que la date de fin par rapport a la date de debut car dans le cas suivant ce deviendrait relou de modifier : 
- j'ai une absence du 1er au 3
- je veux la changer sur 4 au 5
- intuitivement l'utilisateur va vouloir changer la date de debut en premier
- il ne va pas pouvoir
- va donc modifier la date de fin
- puis modifier la date de debut

ce qui fait un aller retour inutile...
Par contre on peut faire en sorte que si on met une date de debut posterieure a la date de fin, ca change la date de fin :)

2021-12-10 13:54 UTC, sophiemoustard requested changes

2021-12-10 13:54 UTC, sophiemoustard commented on src/modules/client/mixins/planningActionMixin.js
> +          endDate: { required, minDate: minDate(this.editedCustomerAbsence?.dates?.startDate) },
l'operateur ? fonctionne bien dans quasar ?

2021-12-10 14:43 UTC, ulysseferreira approved these changes

2021-12-10 17:29 UTC, sophiemoustard requested changes

2021-12-10 17:29 UTC, sophiemoustard commented on src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
> +        <ni-datetime-range caption="Dates et heures de l'absence" :value="editedCustomerAbsence.dates" required-field
tu peux ajouter le propriete `last` pour ajouter de l'espace entre le champ et le bouton

2021-12-10 17:31 UTC, sophiemoustard commented
quand je change l'heure de debut a 12h puis que je veux changer l'heure de fin a 11h le jour suivant, je ne peux pas 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/24521863/145616709-ddb74d1e-78c3-4a41-9472-56eb6ae11612.png">

2021-12-10 17:32 UTC, manonpalin commented on src/modules/client/mixins/planningActionMixin.js
> +          endDate: { required, minDate: minDate(this.editedCustomerAbsence?.dates?.startDate) },
Il ne fonctionne pas toujours bien? 
On l'utilise dans plusieurs fichiers coté webApp, et dans notre cas d'utilisation il fonctionne bien puisque la validation fonctionne bien, non ?

2021-12-13 11:54 UTC, sophiemoustard reviewed
tu pourrais modifier un peu le style pour que l'affichage soit plus harmonieux
sur la classe `date-item` de `DateRange` tu peux enlever le `max-width` et ajouter 
```
/deep/ .q-field__native
      text-align: center
```

2021-12-13 12:49 UTC, sophiemoustard approved these changes

2021-12-13 12:49 UTC, merged