COM-2553 - can remove customer absence
sophiemoustard/compani-webapp pull request #1396
Opened 2021-12-15 15:11 UTC by manonpalin

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [ ] J'ai verifié la fonctionnalite sur mobile -np

- Périmetre interface :  client 

- Périmetre roles : Auxiliaire/Coach/Admin

- Cas d'usage : Je peux supprimer une absence beneficiaire.

2021-12-15 16:59 UTC, KennyCallegari commented on src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
> +        if (e.msg) NotifyNegative('Erreur lors de la suppression de l\'absence bénéficiaire.');
pourquoi ce `if (e.msg)` ?

2021-12-15 16:59 UTC, KennyCallegari commented on src/modules/client/pages/ni/planning/CustomerPlanning.vue
> +      await this.refresh();
tu as besoin du `async await` ?

2021-12-15 17:06 UTC, manonpalin commented on src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
> +        if (e.msg) NotifyNegative('Erreur lors de la suppression de l\'absence bénéficiaire.');
En effet pas nécessaire

2021-12-15 17:08 UTC, manonpalin commented on src/modules/client/pages/ni/planning/CustomerPlanning.vue
> +      await this.refresh();
Je pense que oui car la methode refresh est asynchrone

2021-12-16 07:46 UTC, sophiemoustard requested changes

2021-12-16 07:46 UTC, sophiemoustard commented on src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
> +import NiButton from '@components/Button';
tu peux l'importer en Button simplement (je crois que c'est plutot comme ca qu'on fait)

2021-12-16 08:11 UTC, manonpalin commented on src/modules/client/components/planning/CustomerAbsenceEditionModal.vue
> +import NiButton from '@components/Button';
Oui bien vu !

2021-12-16 08:41 UTC, sophiemoustard approved these changes

2021-12-16 09:40 UTC, KennyCallegari commented on src/modules/client/pages/ni/planning/CustomerPlanning.vue
> +      await this.refresh();
J'ai lu trop vite pardon

2021-12-16 09:42 UTC, KennyCallegari approved these changes

2021-12-16 09:42 UTC, merged