Com 2613
sophiemoustard/compani-webapp pull request #1427
Opened 2022-01-14 11:09 UTC by ulysseferreira

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- [x] J'ai verifié la fonctionnalite sur mobile

- Périmetre interface : vendeur/client

- Périmetre roles : rof/coach/client-admin/vendor-admin

- Cas d'usage : dans le suivi d'une formation, j'affiche les émargements non prévus dans d'autres formations
TESTS : 
FORMATION INTER_B2B
- prendre 2 apprenant (un alenvi, un d'une autre structure) et les émarger dans une autre formation ayant le même sous-programme
- je vois ces émargements côté vendeur
- côté client je ne vois que les émargements de l'apprenant alenvi

FORMATION INTRA
- émarger un des apprenant dans une autre formation ayant le même sous-programme
- je vois ces émargements côté vendeur et côté client

en tant que formateur de la formation je vois ces émargements non prévus

2022-01-14 14:38 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="unsubscribedAttendances.length">
Ici il manque le titre `Attestations de formation`

2022-01-14 15:18 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +          sortable: true,
Est-ce qu'on veut que ce tableau soit friable? (ce n'est pas précisé sur figma) SI jamais on veut pouvoir le trier, quand on clique sur la flèche il ne se passe rien

2022-01-14 16:33 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    <div v-if="unsubscribedAttendances.length">
c'est un autre ticket ça c'est le 2612

2022-01-14 17:12 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +          sortable: true,
en effet j'ai l'impression que la migration vue 3 a cassé le tri (pareil pour le tableau au dessus de la progression eLearning). Je le retire pour le moment vu que c'est pas précisé sur figma

2022-01-17 09:06 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +            <div v-for="attendance in props.row.attendances" :key="attendance._id" :props="props" class="q-my-sm row">
Ici que penses-tu de definir le style `class="q-ma-sm expanding-table-expanded-row"` pour ajouter un peu de marge sur les cotés ?

2022-01-17 09:38 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +            <div v-for="attendance in props.row.attendances" :key="attendance._id" :props="props" class="q-my-sm row">
done

2022-01-17 13:35 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        {
Tu peux tout mettre sur une seule ligne

2022-01-17 13:35 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        {
idem ici

2022-01-17 13:40 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        {
done

2022-01-17 13:41 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        {
done

2022-01-17 13:58 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        const unsubscribedList = await Attendances.listUnsubscribed(query);
Que penses-tu de renommer `unsubscribedList` en `unsubscribedListGroupByTrainees`?

2022-01-17 14:04 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        const unsubscribedList = await Attendances.listUnsubscribed(query);
Je trouve que ca aide a la compréhension du map qui se trouve apres

2022-01-17 14:05 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +          .map(ul => ({
que penses-tu de remplacer `ul` par `traineeId`?

2022-01-17 14:12 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        const unsubscribedList = await Attendances.listUnsubscribed(query);
j'ai mis unsubscribedAttendancesGroupedByTrainees pour qu'on sache que ce sont des émargements qui sont groupés

2022-01-17 14:26 UTC, manonpalin approved these changes

2022-01-17 15:27 UTC, sophiemoustard requested changes

2022-01-17 15:27 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      <div class="text-italic">
tu pourrais mettre un petite marge en dessous de 8px pour aerer

2022-01-17 16:17 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +            </template>
done

2022-01-17 16:17 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      formatDate,
done

2022-01-17 16:21 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      <div class="text-italic">
done

2022-01-18 09:11 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +          </q-td>
done

2022-01-18 09:13 UTC, sophiemoustard approved these changes

2022-01-18 11:24 UTC, merged