Com 2646
sophiemoustard/compani-webapp pull request #1447
Opened 2022-02-02 17:56 UTC by CorentinMartinot

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur / rof

- Cas d'usage : 
  - correction du message d'erreur de conflit sur les noms (depuis le ticket COM-2645)
  - je peux supprimer un financeur 

- Comment tester ? :
  - generer un confilt sur les noms
  - supprimer un financeur

NB: je n'ai pas traité le deuxieme pb de COM-2645, c normal

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-02-03 10:08 UTC, ulysseferreira approved these changes

2022-02-03 16:09 UTC, sophiemoustard requested changes

2022-02-03 16:09 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const validateOrganisationDeletion = (organisationId) => {
tu peux passer une ligne

2022-02-04 09:33 UTC, sophiemoustard approved these changes

2022-02-04 09:42 UTC, merged