COM-2665: add billing item
sophiemoustard/compani-webapp pull request #1453
Opened 2022-02-08 17:09 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur admin/rof

- Cas d'usage : je peux ajouter un article de facturation

- Comment tester ? :
  - ajouter un article de facturation
  - essayer de le réajouter => 409

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-02-09 10:31 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +        NotifyNegative('Erreur lors de la récupération des financeurs.');
"des articles"

2022-02-09 10:34 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const addItem = async () => {
quand on ajoute un article, on se retrouve en haut de la page... Tu sais a quoi c'est du ? 

Je trouve ca dommage, surtout si allonge la page dans le futur.

2022-02-09 10:36 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +        tableLoading.value = true;
Les tables partagent le chargement. Je crois qu'on fait pas ca d'habitude sii ?

2022-02-09 11:09 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +                  :style="col.style">
done

2022-02-09 11:10 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const addItem = async () => {
comment ça en haut de la page ? j'ai pas ça moi 🤔

2022-02-09 11:14 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +        tableLoading.value = true;
done

2022-02-09 14:20 UTC, CorentinMartinot commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const addItem = async () => {
c marrant quand je met `:loading="itemsLoading"` sur les deux tableaux ca m'emmene en haut de la page a la valdation de la moddale et quand je met `:loading="organisationsLoading"` et `:loading="itemsLoading"` ca le fait pas ... 
Tu as le meme comportement ?

Ras du coup, c'est reglé.

2022-02-09 15:34 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const addItem = async () => {
en fait c'est normal que ça le fasse, c'est parce qu'on load les tables  et que du coup le contenu est remplacé par le loader et la height change, donc le focus bouge aussi. Si ça le fait pas c'est que les loaders ont été mal configurés. J'ai un peu modifié les loaders d'ailleurs

2022-02-09 16:46 UTC, CorentinMartinot approved these changes

2022-02-10 08:18 UTC, sophiemoustard requested changes

2022-02-10 08:18 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +          </template>
tu n'as pas besoin de mettre ca

2022-02-10 08:18 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const openItemCreationModal = () => { itemCreationModal.value = true; };
tu peux passer une ligne apres et idem apres la methode resetItemAdditionForm

2022-02-10 09:27 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +          </template>
done

2022-02-10 09:29 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/billing/BillingConfig.vue
> +    const openItemCreationModal = () => { itemCreationModal.value = true; };
done

2022-02-10 11:28 UTC, sophiemoustard approved these changes

2022-02-10 11:30 UTC, merged