COM-2755: can add payment
sophiemoustard/compani-webapp pull request #1525
Opened 2022-04-06 09:01 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : je peux ajouter des règlements à une facture

- Comment tester ? :
  - sur une facture sur la fiche d'une structure ajouter un paiement et un remboursement
  - dérouler le détail de la facture avec les différents règlements affichés

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +export default {
on fait pas les nouveaux cmp en API de composition ?

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      <ni-button class="full-width modal-btn bg-primary" label="Créer le paiement" icon-right="add" color="white"
`créer le ${ creationModalNature }`

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +.test
nom de classe a changer

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +    const getPaymentType = type => PAYMENT_OPTIONS.find(option => option.value !== type).label;
option.value === type

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        <q-td colspan="100%">
Rmq: ca va etre relou l'alignement :(

2022-04-06 10:41 UTC, CorentinMartinot commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        company: courseBill.company._id,
mhmm j'aime pas trop ces deux champs "company" et "courseBilL". EN vrai ce ne sont pas des metainfos. C'est juste une info qu'on affiche pas dans la modale. Je mettrai ces info dans `newCoursePayment`...

De plus pour `company`, on est sur une fiche strucutre, pas besoin de populer l'id dans le back. On l'a deja

2022-04-06 12:32 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      <ni-button class="full-width modal-btn bg-primary" label="Créer le paiement" icon-right="add" color="white"
done

2022-04-06 12:43 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +    const getPaymentType = type => PAYMENT_OPTIONS.find(option => option.value !== type).label;
done

2022-04-06 12:45 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        <q-td colspan="100%">
done

2022-04-06 13:41 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        company: courseBill.company._id,
done

2022-04-06 15:47 UTC, CorentinMartinot commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +            <div v-for="coursePayment in props.row.coursePayments" :key="coursePayment._id" :props="props"
on pourrait trier dans l'ordre chronologique

2022-04-06 15:47 UTC, CorentinMartinot commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      <ni-button class="full-width modal-btn bg-primary" :label="`créer le ${ creationModalNature.toLowerCase() }`"
avec une majuscule a "Créer"

2022-04-06 16:04 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      <ni-button class="full-width modal-btn bg-primary" :label="`créer le ${ creationModalNature.toLowerCase() }`"
done

2022-04-06 16:23 UTC, CorentinMartinot approved these changes

2022-04-07 09:08 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +export default {
je valide ce retour

2022-04-07 09:14 UTC, sophiemoustard reviewed
il faudrait peut etre une phrase pour quand on deplie le tableau est que c'est vide... la ca put faire penser a un bug 
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/24521863/162164805-981136f8-fcd0-4772-80ce-8579f460d566.png">

2022-04-07 09:14 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        });
sur une ligne

2022-04-07 09:14 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        if (validations.value.newCoursePayment.$error) return NotifyWarning('Champ(s) invalide(s)');
tu peux laisser une ligne vide apres

2022-04-07 09:14 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +      },
sur une ligne
tout comme celui d'avant ou tu peux mettre `format: formatPrice`

2022-04-07 10:16 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +        });
done

2022-04-07 10:17 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +      },
done

2022-04-07 12:31 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +export default {
done

2022-04-07 12:55 UTC, sophiemoustard requested changes

2022-04-07 12:55 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      Ajouter un <span class="text-weight-bold">{{ creationModalNature.toLowerCase() }}</span>
je trouve le nom `creationModalNature` un peu etrange... tu pourrais mettre `paymentNature` non ? comme le nom de la constante

2022-04-07 12:55 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const paymentNatureOptions = ref(PAYMENT_NATURE_OPTIONS);
pourquoi créer un reference ici ? tu es obligé ?

2022-04-07 12:55 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const netInclTaxesError = computed(() => {
tu pourrais utiliser une ternaire ici

2022-04-07 12:55 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const hide = () => {
tu pourrais les mettre sur une ligne qu'en penses tu ? (ceux d'en dessous aussi)

2022-04-07 12:58 UTC, sophiemoustard requested changes

2022-04-07 12:58 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      :error-message="netInclTaxesError" />
ca tient sur 3 lignes

2022-04-07 12:58 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +import CoursePaymentCreationModal from '../billing/CoursePaymentCreationModal.vue';
ton format d'import n'est pas le bon

2022-04-07 13:11 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +      Ajouter un <span class="text-weight-bold">{{ creationModalNature.toLowerCase() }}</span>
done

2022-04-07 13:18 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const netInclTaxesError = computed(() => {
done

2022-04-07 13:19 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const creationModalNature = computed(() => {
done

2022-04-07 13:19 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const hide = () => {
done

2022-04-07 13:19 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +  name: 'PaymentCreationModal',
done

2022-04-07 13:21 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +import CoursePaymentCreationModal from '../billing/CoursePaymentCreationModal.vue';
done

2022-04-07 13:22 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +import { positiveNumber } from '@helpers/vuelidateCustomVal';
done

2022-04-07 13:47 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +import { required } from '@vuelidate/validators';
ces 2 la sont des imports de librairies exterieurs - a la difference de @data par exemple qui vient de chez nous. Il faut donc le mettre en dessous de vuex la haut

2022-04-07 13:50 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const paymentNatureOptions = PAYMENT_NATURE_OPTIONS;
par rapport a ma question precedente, pourquoi recreer une variable ? tu peux directement mettre PAYMENT_NATURE_OPTIONS dnas le return non ?

2022-04-07 14:14 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +import { required } from '@vuelidate/validators';
done

2022-04-07 14:17 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CoursePaymentCreationModal.vue
> +    const paymentNatureOptions = PAYMENT_NATURE_OPTIONS;
done

2022-04-08 07:18 UTC, sophiemoustard approved these changes

2022-04-08 07:29 UTC, merged