COM-2792: display estimated start date field
sophiemoustard/compani-webapp pull request #1536
Opened 2022-04-22 13:27 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : je peux ajouter une date de démarrage souhaitée pour une formation

- Comment tester ? :
  - sur la branche dev exporter les formations pour une période donnée
  - faire de même sur cette branche et s'assurer qu'on a bien la même chose (à l'exception de certains champs de "comptage" ou le vide a été remplacé par 0
  - créer une formation avec une date de démarrage dans la période précédemment utilisée et exporter les formations => j'ai bien ma formation dans l'export
  - ajouter un créneau à la formation, en dehors de la période donnée => la date de démarrage ne s'affiche plus sur le profile de la formation + la formation n'est plus dans l'export 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-04-22 14:16 UTC, cmolle reviewed
@ulysseferreira sur le ticket il est precise que c'est etq rof qu'on a acces a ce champs. Ce champs doit-il etre visible/modifiable par les coachs structures ? (actuellement c'est le cas)

2022-04-22 15:02 UTC, ulysseferreira commented
> @ulysseferreira sur le ticket il est precise que c'est etq rof qu'on a acces a ce champs. Ce champs doit-il etre visible/modifiable par les coachs structures ? (actuellement c'est le cas)

bien vu c'est corrigé (en back aussi)

2022-04-22 15:09 UTC, cmolle approved these changes

2022-04-22 15:46 UTC, sophiemoustard requested changes

2022-04-22 15:46 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +          @update:model-value="updateEstimatedStartDate($event)" class="col-4" />
pour la classe ici je pense qu'il vaut mieux que tu l'alignes avec les autres selecteur et champs texte plutot qu'avec les containeur de creneaux, qui ont une taille variable

2022-04-22 15:46 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +          @update:model-value="updateEstimatedStartDate($event)" class="col-4" />
tu pourrais du coup enelver le col-4 et mettre `'col-xs-12 col-md-6'`

2022-04-22 15:46 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +    async updateEstimatedStartDate (value) {
pour rester coherent avec le reste du code, tu pourrais remonter l'evènement au parent qui gere deja la MAJ des champs de la formation qu'en penses tu ?

2022-04-25 08:34 UTC, ulysseferreira commented on src/core/components/courses/SlotContainer.vue
> +          @update:model-value="updateEstimatedStartDate($event)" class="col-4" />
done

2022-04-25 08:41 UTC, ulysseferreira commented on src/core/components/courses/SlotContainer.vue
> +    async updateEstimatedStartDate (value) {
done

2022-04-26 07:41 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> +    async updateEstimatedStartDate (value) {
pourquoi tu n'utilises pas directement updateCourse ? c'etait le but de mon retour initial pardon

2022-04-26 08:32 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +    async updateEstimatedStartDate (value) {
done

2022-04-26 09:24 UTC, sophiemoustard approved these changes

2022-04-26 09:24 UTC, merged