Com 2829
sophiemoustard/compani-webapp pull request #1556
Opened 2022-05-05 07:22 UTC by cmolle

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles :

- Cas d'usage :

- Comment tester ? :

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-06 11:06 UTC, ulysseferreira reviewed
tous les !isEqualTo 0 dans les ifs, on est sûr que la variable est toujours définie ? parce que sinon avant on rentrait pas dans la boucle mais maintenant si

Non bien vu, c'est corrigé

2022-05-06 12:47 UTC, sophiemoustard commented on src/core/helpers/numbers.js
> +
il va peut etre y a avoir des conflits avec une de mes PR ou j'ai mis tous le fichier egalement

2022-05-06 12:51 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +          this.newCreditNote.exclTaxesCustomer = this.newCreditNote.billingItemList.reduce((acc, bi) => {
le bon formatage c'est de mettre `(acc, bi) => {` a la ligne

2022-05-06 12:52 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +          }, 0);
il faut que tu le initialises en '0' non ? ou `toString(0)`

2022-05-06 12:52 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +          }, 0);
idem

2022-05-06 12:57 UTC, sophiemoustard requested changes

2022-05-06 12:57 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        this.newCreditNote.billingItemList.push({ billingItem: '', unitInclTaxes: toString(0), count: 1 });
dnas subscritpion tu le definis en 0 et ici en '0'. pourquoi cette difference ?

2022-05-06 12:57 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        this.newCreditNote.billingItemList.push({ billingItem: '', unitInclTaxes: toString(0), count: 1 });
de plus dans les scripts, tu as enlevé cette  ligne `unitInclTaxes: bi.unitInclTaxes.toString(),`

2022-05-06 12:57 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        this.newCreditNote.billingItemList.push({ billingItem: '', unitInclTaxes: toString(0), count: 1 });
et d'ailleurs a la ligne d'en dessous tu l'as aussi laissé en nombre

2022-05-06 15:24 UTC, manonpalin commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +            ...(cnEvent.bills.careHours && { careHours: cnEvent.bills.careHours.toString() }),
Pour enregistrer `careHours` en bdd sous forme de string

2022-05-06 15:30 UTC, manonpalin commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +          }, 0);
done

2022-05-06 15:31 UTC, manonpalin commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +          }, 0);
done

2022-05-06 15:32 UTC, manonpalin commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +        this.newCreditNote.billingItemList.push({ billingItem: '', unitInclTaxes: toString(0), count: 1 });
Oui pardon j'ai oublié de le modifier ici mais suite a notre discussion d'hier, comme unitInclTaxes est entre par l'utilisateur, on peut l'enregistrer en Number en bdd

2022-05-06 15:38 UTC, manonpalin commented on src/modules/client/pages/ni/billing/CreditNotes.vue
> +            inclTaxesCustomer = parseFloat(add(inclTaxesCustomer, selectedEvents[i].bills.inclTaxesCustomer));
done

2022-05-09 10:17 UTC, ulysseferreira approved these changes

2022-05-10 08:57 UTC, ulysseferreira approved these changes

2022-05-10 10:30 UTC, merged