COM-2861 - add shouldPayHolidays checkbox
sophiemoustard/compani-webapp pull request #1566
Opened 2022-05-17 12:46 UTC by manonpalin

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles :

- Cas d'usage :

- Comment tester ? :

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-17 13:41 UTC, sophiemoustard requested changes

2022-05-17 13:41 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/RhConfig.vue
> +          <div class="col-xs-12 col-md-6">
je crois que tu n'as pas besoin de cette div car elle est deja dans le ni-input

2022-05-17 14:28 UTC, sophiemoustard approved these changes

2022-05-18 09:19 UTC, manonpalin commented on src/modules/client/pages/ni/config/RhConfig.vue
> +  color: $copper-grey-900
@romain m'a dit que ses maquettes ne sont pas a jour sur les couleurs et qu'il faut utiliser les couleurs que l'on a l'habitude d'utiliser

2022-05-18 09:53 UTC, cmolle approved these changes

2022-05-18 10:09 UTC, merged

2022-05-23 15:27 UTC, Romain commented
Bonjour @sophiemoustard @cmolle ,

Je pense que vous m'avez taggé par erreur dans cette PR. Aucun souci là-dessus.

Par contre, m'a curiosité m'a poussé à regarder ce qu'était Compani et je me rends compte que l'intégralité du code source est accessible publiquement, y compris celui de l'API.

Si j'étais mal intentionné je pourrais y chercher une faille, prendre la liste des paquets installés pour identifier ceux qui sont à risque ou à tout le moins facilement mettre en place une attaque de type DDoS en ciblant les routes les plus gourmandes en ressources.

Peut-être devriez-vous rendre ces repos privés ? Sauf à ce que vous souhaitiez vraiment que n'importe qui puisse contribuer à ce projet.

Au plaisir,
Romain