COM-2853: refacto payer
sophiemoustard/compani-webapp pull request #1567
Opened 2022-05-17 14:24 UTC by ulysseferreira

- [ ] ~~J'ai vérifié la fonctionnalité sur mobile~~
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [slite de MES](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/mE8PaaeZN7) et [MEP](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/VSKy3bsY9C) les modifications faites

### POUR TESTER LA PR  :white_check_mark:
- Périmètre interfaces / rôles : vendeur rof/admin

- Cas d'usage : je peux facturer et exporter les formations normalement

- Comment tester ? :
  - faire tourner le script
  - s'assurer que les factures existantes s'affichent et se téléchargent bien 
  - créer une facture avec la structure comme payeur
  - éditer le payeur
  - valider la facture et la télécharger => le payeur s'affiche correctement
  - faire un avoir sur la facture et le télécharger => le payeur s'affiche correctement
  - créer une facture avec un organisme de financement comme payeur
  - éditer le payeur
  - valider la facture et la télécharger => le payeur s'affiche correctement
  - exporter les formations => le payeur s'affiche correctement
  - afficher la liste des factures d'une structure sur la fiche de la structure 

_Si tu as lu cette description, pense a réagir avec un :eye:_

2022-05-18 09:46 UTC, sophiemoustard commented
dans tes cas de tests, j'ajouterais de créer une facture payée par un financeur. Aujourd'hui il n'y en a pas en production du coup on ne peut pas tester ce bout la du script
et on n'est pas a l'abri que certaines soient créées d'ici la

2022-05-18 10:08 UTC, sophiemoustard requested changes

2022-05-18 10:08 UTC, sophiemoustard commented on src/core/components/courses/ProfileBilling.vue
>          await CourseBills.create({
tu pourrais creer une methode pour formater le paylaod ce serait  plus lisible qu'en penses tu ?

2022-05-18 10:08 UTC, sophiemoustard commented on src/core/components/courses/ProfileBilling.vue
> +          {
idem

2022-05-18 12:56 UTC, ulysseferreira commented on src/core/components/courses/ProfileBilling.vue
>          await CourseBills.create({
done

2022-05-18 12:56 UTC, ulysseferreira commented on src/core/components/courses/ProfileBilling.vue
> +          {
done

2022-05-18 14:06 UTC, sophiemoustard commented on src/core/components/courses/ProfileBilling.vue
>          await CourseBills.create({
mon retour concernait tout le payload qu'en penses tu ?

2022-05-19 12:48 UTC, ulysseferreira commented on src/core/components/courses/ProfileBilling.vue
>          await CourseBills.create({
je ne suis pas convain, on n' pas exactement la même chose dans le payload de la création et de l'édition. : on a course et company en plus dans la création donc il faudra mettre une condition là dessus, j'ai peur que ça soit pas super lisible

2022-05-19 16:00 UTC, ulysseferreira commented on src/core/components/courses/ProfileBilling.vue
>          await CourseBills.create({
done

2022-05-20 07:31 UTC, sophiemoustard approved these changes

2022-05-20 08:30 UTC, manonpalin commented on src/core/components/courses/ProfileBilling.vue
> +    const FUNDING_ORGANISATION = 'funding_organisation';
Habituellement on les met plutot dans le fichier `constants.js` non ? (j'imagine que tu vas surement la réutiliser dans tes prochaines PR ?)

2022-05-20 09:57 UTC, ulysseferreira commented on src/core/components/courses/ProfileBilling.vue
> +    const FUNDING_ORGANISATION = 'funding_organisation';
non justement elle sera utilisé que là c'est pour ça que je l'ai mise dans le fichier

2022-05-20 10:27 UTC, manonpalin approved these changes

2022-05-20 12:03 UTC, merged