WIP
sophiemoustard/compani-webapp pull request #1695
Opened 2022-10-31 09:57 UTC by cmolle

2022-10-31 10:06 UTC, cmolle commented on src/modules/vendor/components/programs/StepEditionModal.vue
>      <div class="row items-end">
On avait discuté avec Ulysse de potentiellement ajouté un q-field ici (comme sur dateTimeRange) pour moins s'embeter avec les validations et uniquement afficher une erreur globale pour les champs heures et minutes

2022-10-31 16:47 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/StepEditionModal.vue
>      <div class="row items-end">
done

2022-11-02 09:30 UTC, cmolle commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +      <p :class="['input-caption', { required: requiredField }]">Durée Théorique *</p>
Ici on peut simplifier en `<p class="input-caption required">Durée Théorique</p>`

2022-11-02 09:30 UTC, cmolle commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    const tmpInput = ref({ path: 'minutes', event: 0 });
Que penses-tu de l'appeler currentEditedField plutot que tmpInput ?

2022-11-02 09:30 UTC, cmolle commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    const tmpInput = ref({ path: 'minutes', event: 0 });
Est-ce qu'on pourrait l'initialiser a {} ?

2022-11-02 09:30 UTC, cmolle commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    };
sur une ligne ?

2022-11-02 16:59 UTC, sophiemoustard commented on src/modules/vendor/composables/StepEditionModal.js
> +  const positiveIntDuration = value => value !== 'PT0H0M' && value !== 'PT0S' && value.match(/(PT\d*H\d*M|PT\d*S)/);
est ce sa place ? j'ai l'impression que ca pourrait etre dans un service non pour etre réutilisable facilement

2022-11-02 16:59 UTC, sophiemoustard commented on src/modules/vendor/composables/StepEditionModal.js
> +  const positiveIntDuration = value => value !== 'PT0H0M' && value !== 'PT0S' && value.match(/(PT\d*H\d*M|PT\d*S)/);
le fichier `vuelidateCustomVal` me parait pas mal pour ca

2022-11-02 17:25 UTC, sophiemoustard requested changes

2022-11-02 17:25 UTC, sophiemoustard commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    const updateTmp = (event, path) => { currentEditedField.value = { path, event }; };
j'ai des comportements assez etrange si je rentre une valeur négative dans le champ `minute` puis que je `blur` le champ a plusieurs reprise.
que penses tu de
- remettre à `{}` la variable `currentEditedField` après `update(value, 'theoreticalDuration');`
- de ne faire la maj que si `event` est defini du coup
```
const updateTheoreticalDuration = () => {
    const { path, event } = currentEditedField.value;
    if (event) {
      const value = path === 'hours' ? `PT${event || 0}H${minutes.value}M` : `PT${hours.value}H${event || 0}M`;
      update(value, 'theoreticalDuration');
      currentEditedField.value = {};
    }
  };
```

2022-11-02 17:25 UTC, sophiemoustard commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    const updateTmp = (event, path) => { currentEditedField.value = { path, event }; };
j'ai l'impression que ca regle les comportements étranges

2022-11-03 09:37 UTC, CorentinMartinot commented on src/modules/vendor/composables/StepEditionModal.js
> +  const positiveIntDuration = value => value !== 'PT0H0M' && value !== 'PT0S' && value.match(/(PT\d*H\d*M|PT\d*S)/);
J'aime pas trop l'idée de généraliser cette validation car elle est très spécifique a notre cas. Avec soit une durée explimé en secondes, soit en heures/minutes. Qu'en penses-tu ?

2022-11-03 10:22 UTC, sophiemoustard commented on src/core/helpers/dates/companiDurations.js
> +    },
il manque une ligne

2022-11-03 10:24 UTC, sophiemoustard commented on src/modules/vendor/composables/StepEditionModal.js
> +  const positiveIntDuration = value => value !== 'PT0H0M' && value !== 'PT0S' && value.match(/(PT\d*H\d*M|PT\d*S)/);
pour le cas `value !== 'PT0H0M' && value !== 'PT0S'` je prendrais bien bien la logique `CompaniDate().asSeconds !== 0`

2022-11-03 10:34 UTC, sophiemoustard commented on src/modules/vendor/composables/StepEditionModal.js
> +    editedStep.value = { name: '', theoreticalDuration: 'PT0S' };
que penses tu de mettre `PT0S` en constante ? j'ai peur qu'on le multiplie dans le code et que ce soit moins lisible

2022-11-03 10:59 UTC, sophiemoustard reviewed
Quand on rentre `2` dans heure et `-10` dans minutes, l'affichage se met bien à 1 dans heure et 50 dans minute mais on ne peut par valider la modale.
Est ce un cas qu'on veut corriger ? 
d'un coté je me dis que l'affichage se met bien et on en peut pas valider donc c'est étrange mais de l'autre coté c'est un peu etrange de remplir `-10` dans minutes 🤔

2022-11-03 15:00 UTC, CorentinMartinot commented on src/core/helpers/dates/companiDurations.js
> +    },
done

2022-11-03 15:00 UTC, CorentinMartinot commented on src/modules/vendor/components/programs/StepEditionModal.vue
> +    const updateTmp = (event, path) => { currentEditedField.value = { path, event }; };
done

2022-11-03 15:28 UTC, manonpalin commented on src/modules/vendor/composables/StepEditionModal.js
> +    value.match(/(PT\d*H\d*M|PT\d*S)/);
Plutot que de definir une regex, est-ce qu'on ne pourrait pas creer une methode dans CompaniDuration qui permet de comparer deux durees ?

2022-11-03 15:46 UTC, CorentinMartinot commented on src/modules/vendor/composables/StepEditionModal.js
> +    value.match(/(PT\d*H\d*M|PT\d*S)/);
tu n'as pas bien pull je pense

2022-11-03 15:49 UTC, sophiemoustard requested changes

2022-11-03 15:49 UTC, sophiemoustard commented on src/core/helpers/dates/companiDurations.js
> +    isEquivalentTo (miscTypeOtherDuration) {
a mettre coté API aussi ?

2022-11-03 15:52 UTC, CorentinMartinot commented on src/core/helpers/dates/companiDurations.js
> +    isEquivalentTo (miscTypeOtherDuration) {
c'est fait deja, il faut rebase

2022-11-03 15:55 UTC, CorentinMartinot commented on src/core/helpers/dates/companiDurations.js
> +    isEquivalentTo (miscTypeOtherDuration) {
je l'ai fait d'ailleurs. Mais ca se voit pas sur gihtub

2022-11-03 15:56 UTC, sophiemoustard commented on src/core/helpers/dates/companiDurations.js
> +    isEquivalentTo (miscTypeOtherDuration) {
si tu as deja rebase ta branche c'est bon :)

2022-11-03 16:15 UTC, manonpalin commented on src/modules/vendor/composables/StepEditionModal.js
> +    value.match(/(PT\d*H\d*M|PT\d*S)/);
En effet. 
Mais pourquoi avoir definit une regex plutot qu'une methode qui compare 2 durees ? Je trouve que c'est vraiment implicite qu'avec cette regex on verifie que notre duree est positive

2022-11-04 09:40 UTC, CorentinMartinot commented on src/modules/vendor/composables/StepEditionModal.js
> +    value.match(/(PT\d*H\d*M|PT\d*S)/);
Ici on verifie surtout que les nombres ne sont pas des floats.

2022-11-04 09:47 UTC, cmolle commented on src/core/helpers/dates/companiDurations.js
> +    toHoursAndMinutes () {
A quoi sert cette methode ? J'ai l'impression qu'elle n'est pas utilise 🤔 Si elle l'est, il faudrait aussi l'ajouter cote API.

2022-11-04 09:52 UTC, CorentinMartinot commented on src/core/helpers/dates/companiDurations.js
> +    toHoursAndMinutes () {
effectivement c'est un reste de mes recherches de solution

2022-11-04 10:25 UTC, manonpalin commented on src/modules/vendor/composables/StepEditionModal.js
> +    value.match(/(PT\d*H\d*M|PT\d*S)/);
On verifie les 2 en soit. 
Laissons comme ca, de toute facon dans tous les cas il faudrait utiliser la regex pour verifier que ce sont des entiers, donc je pense que ma solution ne suffit pas.

2022-11-04 10:36 UTC, manonpalin approved these changes

2022-11-04 11:18 UTC, merged