Com 3277
sophiemoustard/compani-webapp pull request #1700
Opened 2022-11-07 14:23 UTC by cmolle

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2022-11-07 16:23 UTC, CorentinMartinot commented on src/core/components/courses/ProfileBilling.vue
> +      <ni-input v-model="course.expectedBillsCount" required-field type="number" @focus="saveTmp()"
je crois qu'il ne faut pas mettre le `type="number"` (comme pour maxTrainees) car sur firefox ca pose pb : le curseur incremente mais la requete ne part pas au blur. (meme si on re-focus et re-blur)

2022-11-08 08:25 UTC, sophiemoustard requested changes

2022-11-08 08:51 UTC, cmolle commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +        expectedBillsCount: '0',
Enfait ces valeurs deviennent des strings à partir du moment où on les modifie car le q-input renvoie des strings. Dans notre cas, comme on voulais que expectedBillsCount soit conservé par le pickBy meme si c'etait 0 j'avais besoin que ce soit un string des le debut. Mais en effet pour que ce soit plus logique, je peux mettre un string aussi pour maxTrainees.

2022-11-08 08:52 UTC, cmolle commented on src/core/components/courses/ProfileBilling.vue
> +    const saveTmp = () => (tmpInput.value = course.value.expectedBillsCount);
Ok ! Je me suis posée la question d'avoir des méthodes très générique pour saveTmp et updateCourse et je m'etais dit que ca permettait d'être plus lisible quand on avait qu'un champs. Mais ca me va de generiser. :)

2022-11-08 09:48 UTC, CorentinMartinot approved these changes

2022-11-08 09:57 UTC, sophiemoustard approved these changes

2022-11-08 10:09 UTC, merged