COM-3317 estimatedStartDate : send update request only on blur
sophiemoustard/compani-webapp pull request #1722
Opened 2022-11-25 17:09 UTC by CorentinMartinot

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2022-11-28 10:40 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +        <ni-date-input caption="Date de démarrage souhaitée" v-model="course.estimatedStartDate"
Peut etre que tu peux mettre en place une variable temporaire qui prend la modification et au moment du blur, tu envoies la variable temporaire dans l'évènement update au parent qu'en penses tu ?

2022-11-28 15:47 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +          @blur="updateEstimatedStartDate()" />
je crois que tu peux simplement mettre `@blur="updateEstimatedStartDate"` i

2022-11-28 16:01 UTC, sophiemoustard commented on src/core/components/courses/SlotContainer.vue
> +    const inputTempEstimatedStartDate = event => emit('update:estimatedStartDate', event);
idem tmp

2022-11-28 16:01 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +    const inputTempMaxTrainees = event => emit('update:maxTrainees', event);
idem tmp

2022-11-28 17:38 UTC, CorentinMartinot commented on src/core/components/courses/SlotContainer.vue
> +          @blur="updateEstimatedStartDate()" />
done

2022-11-28 17:38 UTC, CorentinMartinot commented on src/core/components/courses/ProfileOrganization.vue
>          if (tmpInput.value === value) return;
done

2022-11-28 17:38 UTC, CorentinMartinot commented on src/core/components/courses/ProfileOrganization.vue
> +    const tempCourse = ref({ misc: '', estimateStartDate: '', maxTrainees: '' });
done

2022-11-28 17:38 UTC, CorentinMartinot commented on src/core/components/courses/SlotContainer.vue
> +    const inputTempEstimatedStartDate = event => emit('update:estimatedStartDate', event);
done

2022-11-28 17:38 UTC, CorentinMartinot commented on src/core/components/courses/TraineeTable.vue
> +    const inputTempMaxTrainees = event => emit('update:maxTrainees', event);
done

2022-11-29 07:27 UTC, sophiemoustard requested changes

2022-11-29 07:27 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +    const inputTempMaxTrainees = event => emit('update:maxTrainees', event);
je ne vois pas la modif

2022-11-29 07:27 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> -        if (tmpInput.value === value) return;
pourquoi tu enleves cette ligne ?

2022-11-29 07:28 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> -        if (tmpInput.value === value) return;
cf mon retour [ici](https://github.com/sophiemoustard/compani-webapp/pull/1722#discussion_r1033720108), il faut que tu compares la valeur que tu as modifiée `get(tmpCourse.value, path)` avec la valeur initiale `get(course.value, path)`

2022-11-30 07:18 UTC, sophiemoustard approved these changes

2022-11-30 12:58 UTC, ulysseferreira approved these changes

2022-11-30 12:58 UTC, merged