Com 3354
sophiemoustard/compani-webapp pull request #1761
Opened 2023-02-08 09:30 UTC by cmolle

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-02-09 16:17 UTC, ulysseferreira commented on src/core/components/courses/LearnerCreationModal.vue
>      disableStartDate: { type: Boolean, default: false },
j'ai l'impression qu'on ne passe jamais la props dans le composant parent, on doit pouvoir le retirer

2023-02-09 16:17 UTC, ulysseferreira commented on src/core/composables/learners.js
> +        const hasUserCompanyWithoutEndDate = lastUserCompany && !lastUserCompany.endDate;
il est pas implicitement vrai quoiqu'il arrive !lastUserCompany.endDate ?

2023-02-09 16:17 UTC, ulysseferreira commented on src/core/composables/learners.js
> +        if (company) return handleErrorsForUserWithCurrentCompany(company);
dans quel cas on rentre ici sans être rentré dans hasUserCompanyWithoutEndDate ?

2023-02-09 16:17 UTC, ulysseferreira commented on src/core/components/courses/TraineeContainer.vue
> +      :disable-user-info="!isRofOrAdmin && doesLearnerHaveCurrentCompanyAndCandBeLink" />
les modifs que tu fais sur l'utilisateur ne sont pas pris en compte etq rof (ex : ajouter un numéro de téléphone) + les champs sont aussi activé côté client quand on a un rôle vendeur (je sais pas si c'est voulu)

2023-02-10 07:19 UTC, cmolle commented on src/core/composables/learners.js
> +        const hasUserCompanyWithoutEndDate = lastUserCompany && !lastUserCompany.endDate;
Si tu as raison 🤔 Je trouve que cette méthode est assez complique avec pas mal de cas et serait plutot d'avis de laisser cette precision (meme si elle est redondante) pour qu'elle soit plus simple a comprendre, qu'en penses-tu ?

2023-02-10 07:49 UTC, cmolle commented on src/core/composables/learners.js
> +        if (company) return handleErrorsForUserWithCurrentCompany(company);
Tu as raison on n'y rentrait plus. J'ai pas mal modifie la methode.

2023-02-10 09:57 UTC, ulysseferreira commented on src/core/composables/learners.js
> +      const sameCompany = lastUserCompany.company === loggedUserCompany;
il faudrait peut-être mettre un get, ça pète quand y a pas de company

2023-02-10 10:07 UTC, ulysseferreira approved these changes

2023-02-13 08:43 UTC, sophiemoustard requested changes

2023-02-13 08:43 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const lastUserCompany = userInfo.user.userCompanyList.sort(descendingSortBy('startDate'))[0];
diem la tu modifies par reference le tableau dans `usrInfo` avec la methode `sort`. tu peux utiliser la methode utilitaire `getLastVersion`

2023-02-13 08:43 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const { user } = userInfo;
est ce necessaire ?

2023-02-13 08:43 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const loggedUserCompany = get(loggedUser.value, 'company._id');
idem ?

2023-02-13 08:43 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const sameCompany = lastUserCompany && lastUserCompany.company === loggedUserCompany;
que penses tu de `const sameCompany = get(lastUserCompany, 'company') === get(loggedUser.value, 'company._id');` ?

2023-02-13 08:43 UTC, sophiemoustard commented on src/modules/client/pages/ni/auxiliaries/Directory.vue
> +          const { _id: userId, userCompanyList } = userExistsInfo.user;
est ce necessaire ?

2023-02-13 08:43 UTC, sophiemoustard commented on src/modules/client/pages/ni/auxiliaries/Directory.vue
> +          if (userHasClientRole) return NotifyNegative('Email déjà existant.');
que penses tu d'organiser le code comme suit : 
```
const currentAndFutureCompanies = getCurrentAndFutureCompanies(userCompanyList);
const userHasValidCompany = !currentAndFutureCompanies.length ||
  currentAndFutureCompanies.includes(this.company._id);
if (!userHasValidCompany) return NotifyNegative('Email relié à une autre structure.');

const userHasClientRole = !!get(userExistsInfo, 'user.role.client');
if (userHasClientRole) return NotifyNegative('Email déjà existant.');
```

2023-02-13 09:06 UTC, cmolle commented on src/core/composables/learners.js
> +      const sameCompany = lastUserCompany && lastUserCompany.company === loggedUserCompany;
Meme si ca ne devrait pas arriver, je preferais verifier que au moins une de deux entreprises etaient defini pour eviter le cas undefined === undefined.
Qu'en penses-tu ?

2023-02-13 09:09 UTC, cmolle commented on src/core/composables/learners.js
> +      const lastUserCompany = userInfo.user.userCompanyList.sort(descendingSortBy('startDate'))[0];
Bien vu 🙈 Le idem fait bien reference au meme probleme back ou tu as vu une autre modification par reference en front ?

2023-02-13 10:46 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const lastUserCompany = userInfo.user.userCompanyList.sort(descendingSortBy('startDate'))[0];
c'etait pour le back oui :)

2023-02-13 10:47 UTC, sophiemoustard commented on src/core/composables/learners.js
> +      const sameCompany = lastUserCompany && lastUserCompany.company === loggedUserCompany;
tu as raison !

2023-02-13 11:28 UTC, sophiemoustard approved these changes

2023-02-13 11:29 UTC, merged