Com 3393
sophiemoustard/compani-webapp pull request #1768
Opened 2023-02-15 13:13 UTC by ulysseferreira

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-02-15 14:08 UTC, cmolle commented
Vu ensemble : ce serait mieux que la date de rattachement ne se mette que si la personne est détachée de sa structure dans le futur. 
Normalement pour le modifier il faut changer la condition dans `setNewLearner` --> ajouter la condition `CompaniDate().isBefore(lastUserCompany.endDate)`

2023-02-15 14:13 UTC, cmolle commented
Je ne pense pas que ca vienne de ta pr mais il y a un petit soucis si quelqu'un est : 
a l'EPS de la date x a y 
puis a l'eps de la date y a z 

Si j'essaye de l'ajouter a une formation INTER b2b pour une date a < y --> ca m'indique que le stagiaire est rattachee a une structure jusqu'a la date y

2023-02-15 14:23 UTC, ulysseferreira commented on src/core/composables/learners.js
> +  const newTraineeRegistration = ref(isInterCourse ? { trainee: '', company: '' } : { trainee: '' });
ah oui bien vu, j'ai fait comme ça en bas et j'ai pas pensé à le faire là

2023-02-15 14:34 UTC, ulysseferreira commented on src/core/composables/learners.js
> +      }
` = newLearner.value.company` mais oui bien vu

2023-02-15 17:29 UTC, cmolle commented on src/core/composables/learners.js
> +      if (learnerAlreadyExists.value)newTraineeRegistration.value = { trainee: await updateLearner() };
Il manque un espace apres la parenthese fermante du if

2023-02-16 08:04 UTC, sophiemoustard requested changes

2023-02-16 09:05 UTC, ulysseferreira commented on src/core/composables/learners.js
> +      if (isInterCourse) newTraineeRegistration.value.company = newLearner.value.company;
done

2023-02-16 09:06 UTC, ulysseferreira commented on src/core/composables/learners.js
done

2023-02-16 09:09 UTC, cmolle approved these changes

2023-02-16 09:23 UTC, sophiemoustard approved these changes

2023-02-16 09:23 UTC, merged