COM-3416: can generate contract
sophiemoustard/compani-webapp pull request #1784
Opened 2023-03-16 16:22 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-03-17 11:21 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +    <div v-if="isVendorInterface">
bien vu

2023-03-17 11:22 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +      <ni-banner v-if="missingInfos.length ">
done

2023-03-17 11:22 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +  <training-contract-price-addition-modal v-model="trainingContractPriceAdditionModal"
done

2023-03-17 11:22 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +
done

2023-03-17 11:23 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +import { formatQuantity } from '@helpers/utils';
done

2023-03-17 11:23 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +import useVuelidate from '@vuelidate/core';
done

2023-03-17 11:23 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +    const generateTrainingContract = async () => {
done

2023-03-17 11:25 UTC, ulysseferreira commented on src/core/api/Courses.js
> +  async generate (courseId, payload) {
bien vu c'est un oubli

2023-03-17 11:27 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        const pdfName = `convention_${course.value.subProgram.program.name}_${course.value.companies[0].name}.pdf`;
done

2023-03-17 11:30 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    </div>
done

2023-03-17 11:31 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractPriceAdditionModal.vue
> +      @update:model-value="update" />
done

2023-03-17 14:23 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        const pdfName = `convention_${course.value.subProgram.program.name}_${course.value.companies[0].name}.pdf`;
Comme tu utilises formatDownloadName, tu peux enlever le `_` et mettre un espace a la place comme pour le formattage des autres docs

2023-03-17 14:31 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
Il faudrait peut etre mettre ici le meme commentaire que dans le back ? 🤔

2023-03-17 14:34 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    <template #footer>
Il faudrait ajouter de la marge entre la derniere div et le footer

2023-03-17 14:49 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
done

2023-03-17 14:51 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    <template #footer>
done

2023-03-17 15:17 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
Il faudrait l'adapter du coup sinon ca renvoie a ce fichier ^^

2023-03-17 15:20 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    <div><span class="text-weight-bold">Intervenant(e) :</span>{{ formatIdentity(course.trainer.identity, 'FL') }}</div>
Il manque un espace entre le : et le nom de l'intervenant(e)

2023-03-20 09:36 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
oups done

2023-03-20 11:20 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      <div class="text-weight-bold">Objectifs :</div>
Tu peux mettre un span comme pour les autres titres non ?

2023-03-20 11:20 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +  white-space: pre-wrap
Sur les formations "savoir evoluer en equipe autonome" j'ai l'impression qu'il y a des retours a la ligne qui ont ete rajoute dans les objectifs par les ops 🤔 Ca pourrait etre interessant de savoir pourquoi.

2023-03-20 13:42 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      <div class="text-weight-bold">Objectifs :</div>
c'est pour que les objectifs passent à la ligne

2023-03-20 13:48 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +  white-space: pre-wrap
je demande sur slack

2023-03-20 15:51 UTC, cmolle commented on src/core/components/courses/TrainingContractInfosModal.vue
> +        return [...new Set(fullAddressList)].toString();
Que penses-tu d'utiliser plutot un `join(', ')` pour avoir des espaces entre les virgules ?

2023-03-20 16:02 UTC, sophiemoustard requested changes

2023-03-20 16:02 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
ici comme c'est une computed, tu pourrais mettre `liveDuration` plutot que `compute...` qui renvoie plutot a une methode
sauf si c'est pour garder comme en back ?

2023-03-20 16:02 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return formattedDates.join('');
pourquoi tu ne fais pas directement `return uniqDates.join(' - ')` ?

2023-03-20 16:02 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +        return [...new Set(fullAddressList)].toString();
sur une ligne

2023-03-20 16:19 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +      else if (!course.value.slots.some(slot => slot.address)) infos.push('mininum 1 adresse');
que se passe-t-il si on a que des creneaux distanciels ? c'est normal qu'il n'y ait pas d'adresse dans ce cas

2023-03-20 16:19 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +      else if (!course.value.slots.some(slot => slot.address)) infos.push('mininum 1 adresse');
ce commentaire est a prendre en compte aussi dans le prehandler du back

2023-03-20 16:21 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
il faut que tu prennes en compte le cas ou il n'y a pas de `misc` dans la formation

2023-03-20 16:21 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +      if (!course.value.slots || !course.value.slots.length) infos.push('minimum 1 créneau');
on ne peut pas generer de convention s'il n'y a que des creneaux a planifier ?

2023-03-20 17:07 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +    <div v-if="isAdmin && isVendorInterface && isIntraCourse">
done

2023-03-20 17:08 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +    const computeLiveDuration = computed(() => {
done

2023-03-20 17:09 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return formattedDates.join('');
done

2023-03-20 17:09 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +        return [...new Set(fullAddressList)].toString();
done

2023-03-20 17:09 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return [...new Set(cityList)].toString();
done

2023-03-20 17:13 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +      if (!course.value.slots || !course.value.slots.length) infos.push('minimum 1 créneau');
non

2023-03-20 17:14 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
s'il n'y a pas de misc il y a juste écrit "jusqu'à x stagiaires", il n'y pas besoin de prendre particulièrement en compte le cas, non ?

2023-03-21 07:40 UTC, cmolle approved these changes

2023-03-21 08:11 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
j'ai eu un `undefined jusqu'a x stagiaires" de mon coté
<img width="473" alt="image" src="https://user-images.githubusercontent.com/24521863/226548774-75ab4159-52b1-4f4e-a971-2095cb2a627e.png">

2023-03-21 08:22 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +      else if (!course.value.slots.some(slot => slot.address || slot.meetingLink)) infos.push('mininum 1 adresse');
prends bien en compte 3 cas dans ton code : 
- que des créneaux présentiels
- des créneaux présentiels et distanciels (quid quand le creneau presentiel est a planifier et qu'il y a un creneau distanciel de prevu par exemple ? ou si les 2 sont cales mais que le presentiel n'a pas d'adresse ? )
- que des créneaux distanciels

2023-03-21 08:23 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
ah oups en fait c'est un retour back ca car c'est dans le document PDF

2023-03-21 08:24 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +        ? `(+ ${elearnigDuration.value} de e-learning)`
il faut un espace avant la `(` sinon ca donne 
![Uploading image.png…]()

2023-03-21 08:29 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.slots.length + course.slotsToPlan.length }} créneaux
pour "creneaux" ll faut que tu utilises `formatQuantity` sinon quand il n'y en a qu'un ca fait une faute d'orthigraphe
![image](https://user-images.githubusercontent.com/24521863/226552520-8d0f05bf-2589-41f9-9ddc-3062cc35c3bd.png)

2023-03-21 08:30 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(slotsDuration).format(SHORT_DURATION_H_MM);
tu peux simplifier en `return CompaniDuration(getISOTotalDuration(course.value.slots)).format(SHORT_DURATION_H_MM);` non ?

2023-03-21 08:31 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(slotsDuration).format(SHORT_DURATION_H_MM);
et saute une ligne apres l'accolade fermante `}` du `if`

2023-03-21 08:33 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(elearningDuration).format(SHORT_DURATION_H_MM);
idem ici : pourquoi tu passes par `toISO` puis tu reboucles dans `CompaniDuration` pour formater ? tu pourrais directement faire non ? 
```
return course.value.subProgram.steps
        .filter(step => step.type === E_LEARNING)
        .reduce((acc, step) => acc.add(step.theoreticalDuration), CompaniDuration())
        .format(SHORT_DURATION_H_MM);
```

2023-03-21 08:33 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(elearningDuration).format(SHORT_DURATION_H_MM);
si c'est le cas, idem en back

2023-03-21 09:07 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
c'est dans le pdf que tu as undefined ? j'ai rien de mon côté :/ c'est quelle formation ?

2023-03-21 09:24 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +        ? `(+ ${elearnigDuration.value} de e-learning)`
done

2023-03-21 09:28 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.slots.length + course.slotsToPlan.length }} créneaux
done

2023-03-21 09:29 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(slotsDuration).format(SHORT_DURATION_H_MM);
done

2023-03-21 09:31 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      return CompaniDuration(elearningDuration).format(SHORT_DURATION_H_MM);
done

2023-03-21 10:13 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractInfosModal.vue
> +      {{ course.misc }} jusqu'à {{ course.maxTrainees }} stagiaires
cet id `63bfdc4956a960c579ff8c96`

2023-03-21 10:15 UTC, sophiemoustard reviewed
s'il y a beuacoup de ville differentes dnas les adresses ou que les objectifs pédagogiques sont long l'affichage est etrange : 
![image](https://user-images.githubusercontent.com/24521863/226576399-69320ce2-c94b-4b9e-bf8d-22b0f4fbfd3f.png)
je te propose de le noter dans le ticket et on peut le faire dans une prochaine PR si on veut fusionner celle pour debloquer 


Ulysse : C'est quelle formation ?

Sophie : une que j'ai en local avec 3 adresses dans 3 villes différentes et des objectifs assez longs comme pour le programme "Construire une vision et un cadre pour une organisation autonome"

2023-03-21 11:04 UTC, sophiemoustard approved these changes

2023-03-21 11:04 UTC, merged