Com 3418
sophiemoustard/compani-webapp pull request #1787
Opened 2023-03-21 16:57 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-03-22 09:41 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        <div class="q-mt-md row">
Il y a un probleme d'indentation avec ce div (la balise fermante aussi)

2023-03-22 09:41 UTC, cmolle commented on src/core/components/form/FileUploader.vue
>        return fields;
Qu'est-ce qui ait que dans ce cas on n'a pas besoin des deux autres champs ?

2023-03-22 10:06 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        <div class="q-mt-md row">
done

2023-03-22 10:07 UTC, ulysseferreira commented on src/core/components/form/FileUploader.vue
>        return fields;
le nom je l'ai créé direct dans le helper et le type on en avait besoin pour stocker sur drive mais là on stocke sur cloud storage, je me suis inspiré des feuilles d'émargement et on en a pas besoin j'ai l'impression

2023-03-22 11:13 UTC, cmolle commented
Desolee je pense que c'est un retour par rapport a la pr precedente, mais je me demandais pourquoi quand il n'y a pas de duree theorique et que tous les creneaux ne sont pas rentre, on affiche l'info dans la modale de recapitulatif, puis on affiche l'erreur quand on valide cette modale ? Je me dis que le mettre en info dans la modale laisse penser que c'est une info et non pas un cas d'erreur 🤔 Je me dis que d'un point de vue UX ce serait mieux que l'erreur soit : 
- soit dans le bandeau comme info requise
- soit au moment de l'ouverture de la premiere modale (celle ou on rentre le prix) 

Qu'en penses-tu ?

2023-03-22 13:10 UTC, cmolle approved these changes

2023-03-22 15:59 UTC, sophiemoustard requested changes

2023-03-22 16:45 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +          infos.push('certaines étapes n\'ont pas de durée théorique');
done

2023-03-22 16:47 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +    const url = computed(() => `${process.env.API_HOSTNAME}/trainingcontracts`);
done

2023-03-22 16:49 UTC, ulysseferreira commented on src/core/components/form/FileUploader.vue
> +      return fields.flat();
parce que je passe à la fois des objets ({ name: 'fileName', value: removeDiacritics(this.additionalValue) } et { name: 'type', value: this.name }) et des tableaux (customFields) dans fields

2023-03-23 11:21 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +    const url = computed(() => `${process.env.API_HOSTNAME}/trainingcontracts`);
tu as mis une `ref`. tu ne peux par juste faire une constante clssique ?

2023-03-27 08:04 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +    const url = computed(() => `${process.env.API_HOSTNAME}/trainingcontracts`);
done

2023-03-27 10:27 UTC, sophiemoustard approved these changes

2023-03-27 16:04 UTC, merged