COM-3419: can download training contract
sophiemoustard/compani-webapp pull request #1792
Opened 2023-03-30 10:16 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-03-30 15:58 UTC, sophiemoustard requested changes

2023-03-30 15:58 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
en fait je pense qu'on pourrait mettre ca dans le fichier api

2023-03-30 15:58 UTC, sophiemoustard commented on src/core/components/courses/TrainingContractContainer.vue
> +        } else trainingContracts.value = trainingContractList;
il me semble que quand le `if` est sur plusieurs lignes, on met le `else` aussi sur plusieurs lignes sinon on risque de ne par le voir

2023-03-30 15:58 UTC, sophiemoustard commented on src/core/components/form/FileUploader.vue
> +    hideImage: { type: Boolean, default: false },
a quoi sert cette nouvelle props ?

2023-03-31 08:17 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +      <ni-banner v-if="missingInfos.length && trainingContracts.length < course.companies.length">
Est-ce qu'on l'affiche cote client ?

2023-03-31 08:17 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
Que penses-tu de mettre toute la partie qu'on ne veut pas afficher cote coach dans une section à part ? Je trouve que ce n'est pas clair du premeir coup d'oeil que ce bouton ne s'affiche pas cote coach

2023-03-31 08:17 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
Je ne pense pas qu'on veuille bloquer ici en cas d'archivage 🤔 On ne bloque pas le telechargement des feuilles d'emargement par exemple. Je me dis que s'il y a besoin de la feuille apres l'archivage c'est dommage de bloquer le telechargement. 
Je me pose egalement la question pour la generation de la convention 🤔 En soit vu qu'on ne peut plus la mettre dans Compani ca ne servirait pas a grand chose 🤔 Parcontre si on le fait je me dis qu'il vaut mieux l'ajouter du coup aussi sur les feuilles d'emargement 🤔 Qu'en penses-tu ?

2023-03-31 08:28 UTC, ulysseferreira commented on src/core/components/form/FileUploader.vue
> +    hideImage: { type: Boolean, default: false },
par défaut quand on ne stocke pas le fichier sur le drive on l'affiche sous forme d'image (cf textmedia et titletextmedia dans le catalogue) or on veut pas ça ici surtout que c'est potentiellement un pdf et qu'on ne peut donc pas l'afficher comme image

2023-03-31 08:28 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        } else trainingContracts.value = trainingContractList;
done

2023-03-31 08:40 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
je trouve ça un peu bizarre ça oblie à déclarer TrainingContracts dans le return + transformer l'url en fonction, tu vois ça comment ?

2023-03-31 08:42 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +      <ni-banner v-if="missingInfos.length && trainingContracts.length < course.companies.length">
je ne suis pas sûr de comprendre ta question. Il ne s'affiche pas côté client car on n'affiche côté client la section que lorsqu'il y a une convention uploadée, c'est à dire quand cette condition n'est pas remplie

2023-03-31 08:48 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
ça oblige à mettre 
```
<v-if = vendorInterface>
  <banner>
  <bi color button v-if= intra && ! trainingContracts.length>
</>
<v-if=intra>
  file uploader
</>
```
je sais pas si c'est plus clair, surtout que ça va évoluer de nouveau quand on va afficher l'inter côté client avec le file-uploader, ça me semble peut-être plus juste d'attendre ce moment là pour voir la meilleure imbrication de if pour l'affichage

2023-03-31 08:51 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
je ne suis pas sûr de comprendre ton premier point, je ne bloque pas le téléchargement, juste la génération d'une nouvelle conventon. Je suis d'accord que la génération s'apparente un peu au téléchargement de la feuille d'émargement et qu'il faut le même comportement

2023-03-31 09:03 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
@ulysseferreira que penses-tu d'avoir une methode dans le fichier api > TrainingContracts `getTrainingContractDownloadURL` qui renvoie cette url ?

2023-03-31 09:08 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +      <ni-banner v-if="missingInfos.length && trainingContracts.length < course.companies.length">
Ha oui cote INTRA il n'y a pas de soucis. Par contre cote INTER ce sera possible que ce soit affiché :/

2023-03-31 09:10 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
Que penses-tu en attendant alors de mettre clairement ce qui s'affiche cote client et ce qui s'affiche cote vendeur en ajoutant des conditions sur les elements ? Je trouve vraiment que c'est pas clair ce qui s'affiche ou actuellement.

2023-03-31 09:12 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
Ha pardon j'ai lu trop vite. 
Pour les feuilles d'emargement tu le fias en boyscoot ou il faut qu'on l'ajoute sur notion quelque part ?

2023-03-31 09:54 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
done

2023-03-31 09:55 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
qu'est-ce-qu'on décide du coup ? de ne pas bloquer la génération ou de bloquer le téléchargement de feuille d'émargement ?

2023-03-31 09:55 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +      <ni-banner v-if="missingInfos.length && trainingContracts.length < course.companies.length">
ah oui en effet je corrige

2023-03-31 09:56 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
c'est ce que proposait sophie et c'est ce dont je parle juste au-dessus, je trouve que ça rend un peu bizarre de devoir mettre TrainingContracts dans le return, est-ce une data, computed, méthode ?

2023-03-31 10:23 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
On peut créer une data je pense qui s'initialise grace a la methode ? Du coup on aurait pas besoin de mettre trainingContract dans le return, si ?

2023-03-31 10:29 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
Ca me va de bloquer la generation pour les archivé

2023-03-31 10:35 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
Finalement j'ai l'impression que tu as fait la proposition que tu avais faite dans ton commentaire precedent et que tu ne preferais pas faire pour l'instant. Qu'est-ce qui t'a fait change d'avis ? :)

2023-03-31 10:41 UTC, cmolle commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
Finalement j'ai l'impression que tu as fait la proposition que tu avais faite dans ton commentaire precedent et que tu ne preferais pas faire pour l'instant plutot que mon autre proposition de mettre des conditions en + sur certains elements. Qu'est-ce qui a motivé ce choix ?

2023-03-31 10:52 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
>      const url = `${process.env.API_HOSTNAME}/trainingcontracts`;
done

2023-03-31 10:54 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +        <ni-bi-color-button v-if="!trainingContracts.length" icon="file_download" size="16px"
le fait qu'on risquait d'avoir le bandeau sur inter. Sur les éléments j'ai peur que ça fasse mettre des if partout, je préfère regrouper malgré tout. De toute façon ça va sans doute bouger quand on fera l'inter donc c'est pas définitif

2023-03-31 10:58 UTC, ulysseferreira commented on src/core/components/courses/TrainingContractContainer.vue
> +            <ni-button color="primary" icon="file_download" :disable="disableDocDownload || !!course.archivedAt"
done

2023-03-31 11:14 UTC, cmolle commented on src/core/api/TrainingContracts.js
> +    return `${process.env.API_HOSTNAME}/trainingcontracts`;
Qu'est-ce qui t'a fait choisir le mot `upload` ? 
Je trouve que ca porte un peu à confusion car la méthode ne permet pas de televerser, elle renvoie uniquement l'url qui permet ensuite de televerser.

2023-03-31 14:04 UTC, cmolle approved these changes

2023-04-03 07:13 UTC, sophiemoustard commented on src/core/api/TrainingContracts.js
> +    return `${process.env.API_HOSTNAME}/trainingcontracts`;
c'est `downoload` et non `upload` non ? car la tu la récupères tu ne l'envoies pas

2023-04-03 08:05 UTC, ulysseferreira commented on src/core/api/TrainingContracts.js
> +    return `${process.env.API_HOSTNAME}/trainingcontracts`;
si c'est upload c'est l'url qui permet d'envoyer un nouveau fichier, pour télécharger c'est la méthode refreshtrainingcontract

2023-04-03 08:21 UTC, sophiemoustard commented on src/core/api/TrainingContracts.js
> +    return `${process.env.API_HOSTNAME}/trainingcontracts`;
ah oui pardon

2023-04-03 08:21 UTC, sophiemoustard approved these changes

2023-04-03 08:47 UTC, merged