COM-3461: display holding profile
sophiemoustard/compani-webapp pull request #1817
Opened 2023-05-25 12:30 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-05-25 14:11 UTC, cmolle commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        field: row => row.name,
Comme c'est directement un champs des objets du tableau, tu peux mettre directement 'name' il me semble. 
Tu peux passer la colonne sur une ligne

2023-05-25 14:11 UTC, cmolle commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +    const pagination = ref({ rowsPerPage: 0, sortBy: 'name' });
Est-ce qu'il faut prevoir une pagination ? 🤔 Je crois que domusvi a deja + de 40 structures et il me semble qu'elles sont pas encore toutes rentrées.

2023-05-25 14:11 UTC, cmolle commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        );
une ligne

2023-05-25 14:11 UTC, cmolle commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +    };
A-t-on besoin de ce created ? Ou est-ce que le created dans HoldingProfile peut etre suffisant ? (il me semble que sur ProfileOrga dans ma pr j'avais tout mis dans le parent 🤔

2023-05-25 15:10 UTC, ulysseferreira commented on src/core/api/Holdings.js
> +    const updatedHolding = await alenviAxios.put(`${process.env.API_HOSTNAME}/holdings/${holdingId}`, data);
done, pas besoin en effet

2023-05-25 15:12 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        field: row => row.name,
done

2023-05-25 15:33 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +    const pagination = ref({ rowsPerPage: 0, sortBy: 'name' });
c'est rajouté (à partir de 15 éléments), j'ai dû changer de table parce qu'il n'y a pas de pagination sur responsive table

2023-05-25 15:34 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        );
done

2023-05-25 15:36 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +    };
done

2023-05-26 07:31 UTC, cmolle submitted a review, later dismissed

2023-05-26 09:03 UTC, cmolle approved these changes
Desolee j'ai cru voir un bug sur la pagination mais finalement c'est bon ^^

2023-05-26 11:59 UTC, sophiemoustard requested changes

2023-05-26 11:59 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        :rows-per-page="[15, 50, 100]" class="q-px-md">
pourquoi ne gardes tu pas les valeurs par défaut ?

2023-05-26 11:59 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      <ni-simple-table :data="companyHoldings" :columns="columns" v-model:pagination="pagination"
pourquoi tu n'as pas utilisé un reponsiveTable ?

2023-05-26 11:59 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +              :class="'table-actions-responsive bg-white'">
`table-actions-responsive` cette classe c'est que pour la colonne action non ?

2023-05-26 11:59 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +              <q-item-label @click="goToCompanyProfile(props.row)"
c'est un peu etrange d'utiliser un `q-item-label` sans `q-item` non ? tu peux simplement mettre une div non ?

2023-05-26 12:30 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      },
done

2023-05-26 12:31 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +        :rows-per-page="[15, 50, 100]" class="q-px-md">
done

2023-05-26 12:32 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      <ni-simple-table :data="companyHoldings" :columns="columns" v-model:pagination="pagination"
cf commentaire de Chloé j'ai dû changer de table parce qu'il n'y a pas de ni-pagination sur responsive table

2023-05-26 12:32 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +              :class="'table-actions-responsive bg-white'">
c'est retiré

2023-05-26 12:33 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +              <q-item-label @click="goToCompanyProfile(props.row)"
done

2023-05-26 12:38 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      <ni-simple-table :data="companyHoldings" :columns="columns" v-model:pagination="pagination"
le ni-pagination c'est la pagination cusotm qu'on a fait pour les repertoire et les grands tableaux. mais normalement pour les petits tableau de type `responsive-table` tu as quand même une pagination possible

2023-05-26 12:40 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      <ni-simple-table :data="companyHoldings" :columns="columns" v-model:pagination="pagination"
en fait la simpleTable n'est habituellement pas utilisée dans une carte c'est pour ca que le fond apparait pêche car on l'a forcé avec `isClientInterface ? 'client-header' : 'vendor-header'` dans les class du composant

2023-05-26 12:53 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +      <ni-simple-table :data="companyHoldings" :columns="columns" v-model:pagination="pagination"
le ni-pagination c'est la pagination custom qu'on a fait pour les repertoire et les grands tableaux. mais normalement pour les petits tableau de type `responsive-table` tu as quand même une pagination possible. En creusant un peu, pour qu'elle soit visible il faut passer la props `hide-bottom` avec la valeur `false` 

et comme la pagination par defaut de quasar n'est pas tres belle je pense que tu peux ajouter le composant `ni-pagination` justement dans `responsive-table`

en fait la simpleTable n'est pas utilisée dans une carte c'est pour ca que le fond apparait pêche car on l'a forcé avec `isClientInterface ? 'client-header' : 'vendor-header'` dans les classes du composant

2023-05-26 12:54 UTC, sophiemoustard requested changes

2023-05-26 12:54 UTC, sophiemoustard commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +                :class="['ellipsis', 'clickable-name cursor-pointer']">
du coup ca tient sur une ligne

2023-05-26 13:43 UTC, ulysseferreira commented on src/modules/vendor/components/holdings/ProfileInfo.vue
> +                :class="['ellipsis', 'clickable-name cursor-pointer']">
done

2023-05-26 13:50 UTC, sophiemoustard approved these changes

2023-05-26 14:07 UTC, cmolle commented
J'ai l'impression que la responsive-table ajoute naturellement du padding, du coup le fait d'en avoir ajoute en + rend quelque chose d'un peu etrange. Je pense que tu peux l'enlever du coup 
\

2023-05-26 14:33 UTC, cmolle approved these changes

2023-05-26 14:57 UTC, merged