Com 3469
sophiemoustard/compani-webapp pull request #1818
Opened 2023-05-29 10:21 UTC by cmolle

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-05-29 12:45 UTC, sophiemoustard requested changes

2023-05-29 12:45 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +    rowsPerPage: { type: Array, default: () => [15, 25, 35] },
pourquoi ce changement de nom ?

2023-05-29 12:45 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +    rowsPerPage: { type: Array, default: () => [15, 25, 35] },
je trouve que ca porte a confusion avec le `rowsPerPage` qui est dans pagination

2023-05-29 12:45 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +      return this.hideBottom || (!!this.data.length && this.data.length <= this.rowsPerPage[0]);
pour la props `hide-bottom` est ce qu'on ne pourrais pas la retirer et juste ce dire que si on met `pagination.rowsPerPage: 0` alors ca veut dire qu'on a `hideBottom: true` ?

2023-05-29 14:16 UTC, cmolle commented on src/core/components/table/ResponsiveTable.vue
> +    rowsPerPage: { type: Array, default: () => [15, 25, 35] },
C'est ce qu'on a sur simpleTable et sur tableList, du coup c'etait pour harmoniser. Tu veuc que j'harmonise tout le monde avec rowsPerPageOptions du coup ? :)

2023-05-29 14:21 UTC, cmolle commented on src/core/components/table/ResponsiveTable.vue
> +      return this.hideBottom || (!!this.data.length && this.data.length <= this.rowsPerPage[0]);
Je fais ca :) Est-ce que j'en profite pour changer aussi pour simpleTable ?

2023-05-29 14:26 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +    rowsPerPage: { type: Array, default: () => [15, 25, 35] },
si ce n'est pas trop long je trouverais ca mieux :)

2023-05-29 14:27 UTC, sophiemoustard commented on src/core/components/table/ResponsiveTable.vue
> +      return this.hideBottom || (!!this.data.length && this.data.length <= this.rowsPerPage[0]);
Si ce n'est pas trop compliqué oui vas y :)

2023-05-31 09:33 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/ManualBills.vue
> +    const rowsPerPageOptions = ref([1, 5, 15, 50, 100, 200, 300]);
a-t-on besoin de mettre ces valeurs specifiques ?

2023-05-31 09:33 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/Bills.vue
> +    const rowsPerPageOptions = ref([1, 5, 15, 50, 100, 200, 300]);
meme question

2023-05-31 09:37 UTC, cmolle commented on src/modules/client/pages/ni/billing/ManualBills.vue
> +    const rowsPerPageOptions = ref([1, 5, 15, 50, 100, 200, 300]);
Je suis d'accord ca me paraissait etrange aussi 🤔 Ca me va d'enlever et de prendre les valeurs par defaut mais je me demandais s'il y avait une raison et comme c'etait cote erp j'ai pas trop ose bouger.

2023-05-31 09:47 UTC, sophiemoustard commented on src/modules/client/pages/ni/billing/ManualBills.vue
> +    const rowsPerPageOptions = ref([1, 5, 15, 50, 100, 200, 300]);
je ne pense pas qu'il y ait de raison particulière et quitte a changer cette ligne autant mettre quelque chose de logique non ?

2023-05-31 09:51 UTC, cmolle commented on src/modules/client/pages/ni/billing/ManualBills.vue
> +    const rowsPerPageOptions = ref([1, 5, 15, 50, 100, 200, 300]);
Ok ! Que penses-tu de prendre ce qu'il y a par defaut dans le composant simpleTable ([15, 50, 100, 200, 300]) ?

2023-05-31 12:08 UTC, sophiemoustard approved these changes

2023-05-31 13:43 UTC, cmolle commented on src/modules/client/components/customers/ProfileFollowUp.vue
> +      sortedHelpersPagination: { page: 1, rowsPerPage: 5 },
Oui :) Je t'ai mis une remarque par rapport a ca sur ta pr, tu peux tester sur les tableaux sur la page d'une holding, si tu modifie la pagination d'un des tableaux, ca modifie celles des deux

2023-05-31 14:08 UTC, merged