COM-3467: can display whole holding courses
sophiemoustard/compani-webapp pull request #1822
Opened 2023-06-05 14:41 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-06-05 15:45 UTC, sophiemoustard requested changes

2023-06-05 15:45 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BlendedCoursesDirectory.vue
> +            : { company: get(loggedUser.value, 'company._id') || '' }
si on utilise un `get` pour `company` c'est peut etre plus prudent d'en utiliser aussi un pour `holding` qu'en penses tu ?

2023-06-05 15:45 UTC, sophiemoustard commented on src/core/composables/courseFilters.js
> +export const useCourseFilters = (activeCourses, archivedCourses, isVendorInterface, loggedUser) => {
tu pourrais definir `isVendorInterface` dans la composable non ?

2023-06-05 15:45 UTC, sophiemoustard commented on src/core/composables/courseFilters.js
> +export const useCourseFilters = (activeCourses, archivedCourses, isVendorInterface, loggedUser) => {
et pareil, comme la composable est deja relié au store, tu peux récupérer `loggedUser`

2023-06-05 15:56 UTC, sophiemoustard commented
Cote2 vendeur, on affiche la structure de la formation dans le cas INTRA. Ca pourrait etre bien de le faire aussi pour les admin des sociétés mères qu'en penses tu ?
Si ce n'est pas trop complexe, tu pourrais l'ajouter dans cette PR

2023-06-06 09:07 UTC, ulysseferreira commented on src/core/composables/courseFilters.js
> +export const useCourseFilters = (activeCourses, archivedCourses, isVendorInterface, loggedUser) => {
done

2023-06-06 11:47 UTC, sophiemoustard approved these changes

2023-06-06 12:14 UTC, merged