COM-3505 - can define billing representative of my company
sophiemoustard/compani-webapp pull request #1842
Opened 2023-07-17 15:14 UTC by manonpalin

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-07-18 13:50 UTC, sophiemoustard requested changes

2023-07-18 13:50 UTC, sophiemoustard commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +    this.refreshBillingRepresentativeOptions();
ici tu peux faire du coup : 
```
const promises = [this.refreshCompany(), this.refreshBillingRepresentativeOptions()];
if (this.canUpdateErpConfig) promises.push(this.getEstablishments()]);
await Promises.all(promises); 
```
qu'en penses tu ?

2023-07-18 15:16 UTC, manonpalin commented on src/modules/client/pages/ni/config/CompanyConfig.vue
> +      tmpBillingRepresentative.value = { _id: '' };
Yes, c'est corrigé

2023-07-19 08:38 UTC, sophiemoustard approved these changes

2023-07-19 11:58 UTC, merged