Com 3525 rebase
sophiemoustard/compani-webapp pull request #1868
Opened 2023-08-31 15:58 UTC by manonpalin

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-04 10:46 UTC, sophiemoustard requested changes

2023-09-04 10:46 UTC, sophiemoustard commented on src/core/components/questionnaires/cards/TitleTextMedia.vue
> +
a enlever

2023-09-04 10:46 UTC, sophiemoustard commented on src/core/components/questionnaires/cards/TitleTextMedia.vue
> +
a enlever

2023-09-04 12:06 UTC, sophiemoustard approved these changes

2023-09-05 08:34 UTC, ulysseferreira approved these changes

2023-09-05 08:34 UTC, merged