Com 3542
sophiemoustard/compani-webapp pull request #1869
Opened 2023-09-01 09:20 UTC by manonpalin

- [ ] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-01 10:14 UTC, manonpalin commented
Pour une formation inter, dans le tableau des stagiaires, on n'affiche pas les colonnes je ne sais aps si ce sera clair que ce code correspond au code de 1ere connexion a l'app...

2023-09-04 11:53 UTC, ulysseferreira approved these changes

2023-09-04 14:47 UTC, sophiemoustard requested changes

2023-09-04 14:47 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +        field: row => get(row, 'loginCode'),
tu peux juste mettre `field: 'loginCode'`

2023-09-04 14:47 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +        value: value => value,
pourquoi cette ligne ?

2023-09-04 14:47 UTC, sophiemoustard commented on src/core/components/courses/TraineeTable.vue
> +        value: value => value,
memes retours

2023-09-04 14:47 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +        label: 'Code de 1ère connexion à l\'app ',
je pnse que tu peux alléger en mettant 'Code de connexion à l\'app'

2023-09-04 14:47 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +        label: 'Code de 1ère connexion à l\'app ',
et tu peux enlever l'espace a la fin

2023-09-05 08:48 UTC, sophiemoustard approved these changes

2023-09-05 08:48 UTC, merged