COM-3539: holding admin as company representative
sophiemoustard/compani-webapp pull request #1870
Opened 2023-09-01 15:42 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-04 14:36 UTC, manonpalin approved these changes

2023-09-06 08:51 UTC, sophiemoustard requested changes

2023-09-06 08:51 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
>            companyRepresentativeOptions.value = [];
sur la ligne du dessus, peux tu renommer `isTrainer` en  `loggedUserIsTrainer` stp ?

2023-09-06 14:24 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
>            companyRepresentativeOptions.value = [];
done

2023-09-06 15:05 UTC, sophiemoustard submitted a review, later dismissed

2023-09-06 15:15 UTC, sophiemoustard approved these changes

2023-09-06 15:30 UTC, merged