COM-3559: can update company representative
sophiemoustard/compani-webapp pull request #1878
Opened 2023-09-27 16:05 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-09-28 10:39 UTC, manonpalin commented on src/core/helpers/ability.js
> +  const vendorRole = get(role, 'vendor.name');
Que penses-tu de definir "vendorRole" dans le if(isVendorInterface) ?
Idem pour holdingRole, tu pourrais le definir dans le else

2023-09-28 10:47 UTC, manonpalin commented on src/core/components/courses/ProfileOrganization.vue
>          const clientsUsersAllowedtoAccessCompany = course.value.type === INTRA
TU pourrais sauter une ligne ici

2023-09-28 12:00 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +  const vendorRole = get(role, 'vendor.name');
done

2023-09-28 12:05 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
>          const clientsUsersAllowedtoAccessCompany = course.value.type === INTRA
done

2023-09-29 08:33 UTC, manonpalin commented on src/core/components/courses/ProfileOrganization.vue
> +      if (isIntraCourse.value || (isIntraHoldingCourse.value && (isVendorInterface || hasHoldingRole.value))) {
Ici pourquoi mettre isVendorInterface ? On pourrait plutot mettre `isRofOrVendorAdmin` non ?

2023-09-29 10:06 UTC, sophiemoustard requested changes

2023-09-29 10:06 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> +      if (isIntraCourse.value || (isIntraHoldingCourse.value && (isVendorInterface || hasHoldingRole.value))) {
ets ce qu'o ne pourrait pas utiliser la constante `canUpdateCompanyRepresentative` finalement ? car on n'a besoin de cette liste que pour l'édition non ?

2023-09-29 10:06 UTC, sophiemoustard commented on src/core/helpers/ability.js
> +  const { can, rules } = new AbilityBuilder(createMongoAbility);
ce n'est pas etrange ici de passer methode en argument ?

2023-09-29 10:06 UTC, sophiemoustard commented on src/core/helpers/ability.js
> +    can('update', 'Course', 'company_representative', { type: { $in: [INTRA] } });
tu n'as pas besoin des $in ici

2023-09-29 10:06 UTC, sophiemoustard commented on src/core/helpers/ability.js
> +      can('update', 'Course', 'company_representative', { type: { $in: [INTRA_HOLDING] } });
idem

2023-09-29 10:06 UTC, sophiemoustard commented on src/core/helpers/ability.js
> +  return createMongoAbility(rules);
tu peux passer une ligne avant

2023-09-29 10:08 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +      if (isIntraCourse.value || (isIntraHoldingCourse.value && (isVendorInterface || hasHoldingRole.value))) {
bien vu

2023-09-29 10:13 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +  const { can, rules } = new AbilityBuilder(createMongoAbility);
j'ai juste suivi la doc https://casl.js.org/v6/en/guide/restricting-fields

2023-09-29 10:13 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +    can('update', 'Course', 'company_representative', { type: { $in: [INTRA] } });
done

2023-09-29 10:13 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +      can('update', 'Course', 'company_representative', { type: { $in: [INTRA_HOLDING] } });
done

2023-09-29 10:14 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +  return createMongoAbility(rules);
done

2023-09-29 13:41 UTC, manonpalin approved these changes

2023-09-29 14:23 UTC, sophiemoustard approved these changes

2023-09-29 14:25 UTC, merged