COM-3556: can add trainee
sophiemoustard/compani-webapp pull request #1882
Opened 2023-10-02 15:59 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-04 10:29 UTC, manonpalin commented on src/core/components/courses/TraineeContainer.vue
>          <ni-button v-if="canUpdateCompany" color="primary" icon="add" label="Rattacher une structure" :disable="loading"
En le voyant ecrit, je me demande pourquoi on a pas ecrit `canUpdateCompanies` plutot que `canUpdateCompany` , que penses-tu de le changer ici meme si tu n'as pas ajouté ce champ dans la PR ?

2023-10-04 12:14 UTC, ulysseferreira commented on src/core/components/courses/TraineeContainer.vue
>          <ni-button v-if="canUpdateCompany" color="primary" icon="add" label="Rattacher une structure" :disable="loading"
done

2023-10-04 14:15 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +    can('read', 'Course', 'trainees');
done

2023-10-04 14:26 UTC, manonpalin approved these changes

2023-10-04 15:49 UTC, sophiemoustard requested changes

2023-10-04 15:49 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> +    <ni-trainee-container :can-update-trainees="canUpdateTrainees" :loading="courseLoading"
comme c'est un ability maintenant, on pourrait la definir directement dans le composant non ? ca eviterait de passer une props en plus

2023-10-04 15:49 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> +    <ni-trainee-container :can-update-trainees="canUpdateTrainees" :loading="courseLoading"
tout comme on ne passe par `course` mais on la recupère du store dans le composant

2023-10-04 15:49 UTC, sophiemoustard commented on src/core/components/courses/TraineeContainer.vue
> +              :trainees="traineesGroupedByCompanies[props.row._id]" :can-edit="canUpdateTrainees"
idem ici : je pense que tu pourrais le recupérer dans le composant pour limiter les props

2023-10-04 16:22 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +    <ni-trainee-container :can-update-trainees="canUpdateTrainees" :loading="courseLoading"
j'y pensais mais j'avais l'impression que c'était plus opti de créer une fois la computed et de la faire circuler que de créer plusieurs fois la même computed, qu'en penses-tu ?

2023-10-04 16:31 UTC, sophiemoustard commented on src/core/components/courses/ProfileOrganization.vue
> +    <ni-trainee-container :can-update-trainees="canUpdateTrainees" :loading="courseLoading"
ah bonne question ... tu pourrais regarder un peu ?
et en fait je me demande si tu as besoin de creer une computed 🤔 une fois que tu es sur la page, ce ne sont pas des valeur qui sont amené a change non ?

du coup, la question c'est : vaut il mieux créer une constante et la passer partout en props ou creer cette constante partout ? en terme de perf

2023-10-05 08:29 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> +    <ni-trainee-container :can-update-trainees="canUpdateTrainees" :loading="courseLoading"
je l'ai retiré parce que ça faisait du props drilling (le fait de passer une props à plusieurs composants), après je saurais pas trop dire si y avait pas eu ça quel serait le meilleur cas. Ca oblige à mettre un tracker sur les datas utilisés dans la computed à chaque fois (course et loggedUser), mais dans ce cas c'est pas trop coûteux

2023-10-05 09:06 UTC, sophiemoustard approved these changes

2023-10-05 09:42 UTC, merged