COM-3567: can create intra_holding course
sophiemoustard/compani-webapp pull request #1890
Opened 2023-10-12 09:41 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-12 12:37 UTC, sophiemoustard requested changes

2023-10-12 12:37 UTC, sophiemoustard commented on src/core/composables/courseFilters.js
> +    { label: 'Intra société mère', value: INTRA_HOLDING },
tu pourrais reutiliser `COURSE_TYPES` pour eviter le doublon non ?

2023-10-12 12:37 UTC, sophiemoustard commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +          }),
tu peux le mettre sur une ligne non ?

2023-10-13 07:10 UTC, manonpalin commented on src/modules/vendor/components/courses/CourseCreationModal.vue
> +    isIntraCourse () { return this.newCourse.type === INTRA; },
Je me demande si on ne pourrait pas juste mettre `isIntra` et `isIntraHolding` ? Qu'en penses-tu ?

2023-10-13 09:16 UTC, ulysseferreira commented on src/core/composables/courseFilters.js
> +    { label: 'Intra société mère', value: INTRA_HOLDING },
done

2023-10-13 09:17 UTC, ulysseferreira commented on src/modules/vendor/pages/ni/management/BlendedCoursesDirectory.vue
> +          }),
done

2023-10-13 10:34 UTC, manonpalin approved these changes

2023-10-16 06:59 UTC, sophiemoustard approved these changes

2023-10-16 06:59 UTC, merged