COM-3575 - can choose sending email at coach account creation
sophiemoustard/compani-webapp pull request #1891
Opened 2023-10-12 10:11 UTC by manonpalin

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-12 13:17 UTC, ulysseferreira commented on src/core/components/table/CoachList.vue
> +      get,
peut-être plutôt le mettre dans methods non ?

2023-10-12 14:21 UTC, manonpalin commented on src/core/components/table/CoachList.vue
> +      get,
Ah oui pardon !

2023-10-16 07:14 UTC, sophiemoustard requested changes

2023-10-16 07:14 UTC, sophiemoustard commented on src/core/components/table/CoachCreationModal.vue
> +    <q-checkbox v-if="canSendEmail" label="Envoyer un email à la création du compte"
tu peux utiliser la props `dense` sur la checkbox pour enlever les marges autour et que ce soit aligné a gauche

2023-10-16 07:14 UTC, sophiemoustard commented on src/core/components/table/CoachCreationModal.vue
> +      :model-value="newCoach.sendEmail" @update:model-value="update($event, 'sendEmail')" class="q-pb-md" />
je pense qu'il vaut mieux raisonner en margin que en padding de manière générale

Et tu peux utiliser les classes `class="margin-input last"` pour faire comme pour l'input et ajouter la meme marge en dessous que ce soit une checkbox ou un input

2023-10-16 07:36 UTC, manonpalin commented on src/core/components/table/CoachCreationModal.vue
> +    <q-checkbox v-if="canSendEmail" label="Envoyer un email à la création du compte"
Corrigé

2023-10-16 07:40 UTC, manonpalin commented on src/core/components/table/CoachCreationModal.vue
> +      :model-value="newCoach.sendEmail" @update:model-value="update($event, 'sendEmail')" class="q-pb-md" />
corrigé

2023-10-16 08:08 UTC, sophiemoustard approved these changes

2023-10-16 08:11 UTC, merged