COM-3581: can get attendances
sophiemoustard/compani-webapp pull request #1894
Opened 2023-10-19 08:48 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-19 12:29 UTC, manonpalin commented on src/core/components/courses/ProfileOrganization.vue
> -      isIntraOrVendor,
Tu peux aussi supprimer isIntraCourse non ?

2023-10-19 13:10 UTC, ulysseferreira commented on src/core/components/courses/ProfileOrganization.vue
> -      isIntraOrVendor,
done

2023-10-19 13:48 UTC, manonpalin approved these changes

2023-10-19 15:21 UTC, sophiemoustard requested changes

2023-10-19 15:21 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +    const canAccessTrainee = computed(() => {
tu pourrais mutualiser avec les 2 en ref + une methode `defineCourseAbilities` appelée dans le `created` comme on a fait dans les autres composant

2023-10-19 15:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/index.vue
> +                    <router-link :to="goToLearnerProfile(props.row)">{{ col.value }}</router-link>
si tu ctrl + click tu n'arrives pas sur le bon onglet ; ce qui est logique car dans le nouvel onglet tu n'as plus l'historique de navigation > il faut que tu passes `query: { defaultTab: 'courses' }` dans le retour de la methode `goToLearnerProfile`

2023-10-19 15:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/index.vue
> +                    <router-link :to="goToLearnerProfile(props.row)">{{ col.value }}</router-link>
ce retour est valable pour tous les `router-link` que tu mets

2023-10-19 15:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/index.vue
> +                    <router-link :to="goToLearnerProfile(props.row)">{{ col.value }}</router-link>
et je pense que du coup tu peux enlever la condition dans le fichier route

2023-10-19 15:24 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +            <div v-if="canAccessTrainee" :class="['name', 'clickable-name']" @click="$event.stopPropagation()">
et pourquoi le format de class en tableau et pas en chaine de caractère directement ?

2023-10-19 15:48 UTC, ulysseferreira commented on src/core/components/learners/ProfileCourses.vue
> +                <div @click.stop="goToCourseProfile(props)" class="clickable-name">{{ col.value }}</div>
done

2023-10-19 15:49 UTC, ulysseferreira commented on src/core/components/courses/ElearningFollowUpTable.vue
> +            <div v-if="canAccessTrainee" :class="['name', 'clickable-name']" @click="$event.stopPropagation()">
je ne peut pas mettre @click="$event.stopPropagation()" sur router-link

2023-10-19 15:53 UTC, ulysseferreira commented on src/core/components/courses/ElearningFollowUpTable.vue
> +    const canAccessTrainee = computed(() => {
canReadLearnerInfo n'est pas utilisé, je l'ai retiré du coup

2023-10-20 07:16 UTC, sophiemoustard commented on src/core/components/courses/ElearningFollowUpTable.vue
> +            <div v-if="canAccessTrainee" :class="['name', 'clickable-name']" @click="$event.stopPropagation()">
et pourquoi as ton besoin de cet evenement ?

2023-10-20 07:19 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/index.vue
> +                    <router-link :to="goToLearnerProfile(props.row)">{{ col.value }}</router-link>
ah oui bien vu !

2023-10-20 07:31 UTC, sophiemoustard requested changes

2023-10-20 07:31 UTC, sophiemoustard commented on src/core/components/learners/ProfileCourses.vue
> +      };
dans ce cas, quand je CTRL + click je n'arrive pas sur le bon onglet ...

2023-10-20 07:49 UTC, ulysseferreira commented on src/core/components/courses/ElearningFollowUpTable.vue
> +            <div v-if="canAccessTrainee" :class="['name', 'clickable-name']" @click="$event.stopPropagation()">
sinon on ne stoppe pas la propagation de l'événement quand on clique sur le nom d'un stagiaire, sa progression s'ouvre et on est redirigé vers son profil, alors qu'on voudrait juste être redirigé

2023-10-20 07:52 UTC, ulysseferreira commented on src/core/components/learners/ProfileCourses.vue
> +      };
done

2023-10-20 09:45 UTC, merged