COM-3582: can get potential trainees
sophiemoustard/compani-webapp pull request #1896
Opened 2023-10-19 13:08 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-10-20 08:13 UTC, manonpalin commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
Il ne me semble pas qu'on ai discuté de l'aspect factu ? Pcq si qqn ajoute un stagiaire qui n'est inscrit a aucune autre formation ca va poser pb au niveau de la factu.
Je suis dacc que Léa a évoqué le besoin de pouvoir ajouter tous les stagiaires de la societe mere mais je ne me souviens pas qu'on ai discuté de l'implication que ca a

2023-10-23 08:47 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
c'est ajouté

2023-10-23 11:56 UTC, manonpalin commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
Peux-tu mettre ici l'echange que tu as eu avec Lea stp ?

2023-10-23 13:53 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
![Capture d’écran 2023-10-23 à 15 53 13](https://github.com/sophiemoustard/compani-webapp/assets/70574422/3cbe20b8-1545-4d01-9869-a8fbd5673b62)

2023-10-24 07:21 UTC, sophiemoustard requested changes

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
est ce qu'on ne voudrait pas plutot populer la société mère dans la formation ?
En fait je me dit qu'on pourrait en avoir besoin a d'autres endroits : on pourrait notamment mettre le nom de la société mère dans le nom de la formation par exemple (comme ce qu'on fait pour les intra avec la structure)

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>        if (isClientInterface) {
je trouve toute cette méthode compliquée à lire ...
je te propose ces quelques améliorations : 
- dans plusieurs cas on a besoin des id des structures de la formations, qu'on filtre ensuite ou non ; on pourrait créer une constante `const courseCompanyIds = course.value.companies.map(c => c._id)` pour en pas repeter. 
-> a utiliser dans le cas  `if (course.value.type === INTRA)`, le `else if (get(loggedUser.value, 'role.holding'))`, et le `else` tout a la fin
- le `push` peut etre interessant quand on peut passer dans plusieurs conditions ; or ici ce n'est pas le cas... tu pourrais du coup definir `companies` avec un `let` et ensuite remplacer les `push` par des `=`

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>          } else companies.push(get(loggedUser.value, 'company._id'));
si le `if` ou le `else if` ne sont pas sur une ligne il me semble qu'on ne met pas le else sur une ligne

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +      } else companies.push(...course.value.companies.map(c => c._id));
idem ici

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>        potentialTrainees.value = !isEmpty(companies)
tu peux laisser une ligne vide au dessus pour aerer un peu

2023-10-24 07:21 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
on est d'accord qu'en pratique, on peut quand meme avoir des emargements non prevus sans que l'apprenant soit inscrit a une autre formation avec le cas suivant :
- j'inscris un apprenant
- je l'emarge
- je le désinscrit

2023-10-24 08:12 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
@sophiemoustard oui, je me suis dit qu'on pouvait laisser ça, ça permettait d'avoir la souplesse qu'on veut en magouillant un peu, tout en ayant le blocage en premier lieu

2023-10-24 08:20 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>        if (isClientInterface) {
done

2023-10-24 08:21 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>          } else companies.push(get(loggedUser.value, 'company._id'));
done

2023-10-24 08:21 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +      } else companies.push(...course.value.companies.map(c => c._id));
done

2023-10-24 08:21 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
>        potentialTrainees.value = !isEmpty(companies)
done

2023-10-24 09:26 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
yes ca me va ! je voulais juste etre sure que c'etait bien noté comme possibilité

2023-10-24 09:28 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +          }
sur une ligne

2023-10-24 09:29 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +          if (course.value.type === INTRA_HOLDING) companies = get(loggedUser.value, 'holding.companies');
que penses tu de creer une constante holdingCompanies pour alleger aussi ?

2023-10-24 09:30 UTC, sophiemoustard commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +        const holding = await Holdings.getById(course.value.holding);
ok ca me va de faire comme ca !

2023-10-24 10:22 UTC, manonpalin approved these changes

2023-10-24 11:55 UTC, ulysseferreira commented on src/core/components/table/AttendanceTable/Composables/Attendances.js
> +          if (course.value.type === INTRA_HOLDING) companies = get(loggedUser.value, 'holding.companies');
done

2023-10-24 12:28 UTC, sophiemoustard approved these changes

2023-10-24 12:32 UTC, merged