COM-3614: change course credit note model from company to companies
sophiemoustard/compani-webapp pull request #1905
Opened 2023-11-08 10:01 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-09 16:22 UTC, manonpalin commented on src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
> +      <div>Facture pour le compte de {{ creditNoteMetaInfo.companiesName }}</div>
Plutot "Avoir pour le compte de ..." non ?

2023-11-09 16:56 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CourseCreditNoteCreationModal.vue
> +      <div>Facture pour le compte de {{ creditNoteMetaInfo.companiesName }}</div>
en effet

2023-11-09 17:16 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CourseBillingCard.vue
> +        courseName: `${get(course, 'value.subProgram.program.name')}
tu pourrais utiliser la methode `composeCourseName` non ?

2023-11-10 09:17 UTC, ulysseferreira commented on src/modules/vendor/components/billing/CourseBillingCard.vue
> +        courseName: `${get(course, 'value.subProgram.program.name')}
done

2023-11-10 10:16 UTC, manonpalin approved these changes

2023-11-10 14:31 UTC, sophiemoustard requested changes

2023-11-10 14:31 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CourseBillingCard.vue
>        };
ca tient sur une ligne

2023-11-10 14:31 UTC, sophiemoustard commented on src/modules/vendor/components/billing/CourseBillingCard.vue
>        };
cet objet tient aussi su une ligne d'ailleurs

2023-11-10 14:49 UTC, sophiemoustard approved these changes

2023-11-10 15:10 UTC, merged