Com 3620
sophiemoustard/compani-webapp pull request #1906
Opened 2023-11-10 09:32 UTC by manonpalin

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] J'ai ajouté une variable d'environnement
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2023-11-10 16:16 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      <ni-bi-color-button v-if="isRofOrVendorAdmin && !isClientInterface" icon="file_download"
est-ce-qu'on utilserait pas ability ?

2023-11-13 08:35 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +      <ni-bi-color-button v-if="isRofOrVendorAdmin && !isClientInterface" icon="file_download"
On peut, c'est ajouté

2023-11-13 11:30 UTC, ulysseferreira commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +    const defineCourseAbilities = () => {
il y aura d'autres abilites définie par la suite ? si y en a qu'une seule la fonction est peut-être pas nécessaire, une computed suffit

2023-11-14 16:31 UTC, ulysseferreira approved these changes

2023-11-15 11:01 UTC, sophiemoustard requested changes

2023-11-15 11:01 UTC, sophiemoustard commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        @click="downloadCompletionCertificates(OFFICIAL)" />
tu peux ajouter une marge entre les 2 boutons, ils sont tres collés je trouve

2023-11-15 14:56 UTC, manonpalin commented on src/core/components/courses/ProfileTraineeFollowUp.vue
> +        @click="downloadCompletionCertificates(OFFICIAL)" />
corrigé

2023-11-16 09:10 UTC, sophiemoustard approved these changes

2023-11-16 15:28 UTC, sophiemoustard approved these changes

2023-11-16 15:28 UTC, merged