COM-3671: can display course bills
sophiemoustard/compani-webapp pull request #1967
Opened 2024-03-19 10:12 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2024-03-19 13:49 UTC, manonpalin commented on src/modules/vendor/components/companies/ProfileBilling.vue
> +  name: 'BillingInfos',
Plutot `ProfileBiling` non ?

2024-03-19 13:52 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      if (hasHoldingRole.value) return selectedCompany.value;
Ici tu pourrais utilliser une ternaire pour l'ecrire sur une seule ligne non ?

2024-03-19 13:54 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const holdingCompanies = ref([]);
Pourquoi as-tu besoin de 2 ref (holdingCompanies et companiesOptions) tu pourrais tout le temps travailler avec companiesOptions non ?

2024-03-19 13:57 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if ($store.state.company.company) selectedCompany.value = $store.state.company.company;
Je ne comprends pas ce if, dans quel cas on y passe ?

2024-03-19 13:59 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if (company.value._id) await $store.dispatch('company/fetchCompany', { companyId: company.value._id });
Est-ce que c'est pas plus logique de travailler avec selectedCompany ici ?

2024-03-19 14:02 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      <course-billing-infos v-if="company._id" :company="company" @refresh-company="refreshCompany" />
ce v-if est necessaire ? Il fait doublon avec celui dans CourseBillingInfos non ?

2024-03-19 14:03 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      <ni-select v-if="hasHoldingRole" caption="Structure" :model-value="selectedCompany._id"
Est-ce qu'on le rendrait pas clearable ?

2024-03-19 14:04 UTC, manonpalin commented on src/core/helpers/ability.js
> +const getHoldingAbilities = role => roleBasedAccessControl[role].map(r => r.name);
C'est la meme chose que `getVendorAbilities` ?

2024-03-19 14:12 UTC, manonpalin commented
Quand on navigue sur d'autres pages et qu'on revient sur la page des factures, le selecteur n'est pas réinitialisé

2024-03-19 14:39 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      if (hasHoldingRole.value) return selectedCompany.value;
done

2024-03-19 14:44 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const holdingCompanies = ref([]);
non parce que sinon ce qu'on stocke dans selectedCompany via setCompany y a pas les bonnes infos, dans companiesOptions on a que le label et l'id, on a pas le billingRepresentative par exemple

2024-03-19 14:45 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if ($store.state.company.company) selectedCompany.value = $store.state.company.company;
c'est pour que quand on clique sur une formation et qu'on revient en arrière on ait toujours la structure de sélectionnée. On va la chercher dans le store où elle est encore enregistrée et du coup on a pas à la resélectionné avec le sélecteur

2024-03-19 14:47 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if (company.value._id) await $store.dispatch('company/fetchCompany', { companyId: company.value._id });
ça revient au même non ? qu'est-ce-qui te fait pencher pour selectedCompany ? L'idée c'est de garder selectedCompany pour la définition de la structure dans le sélecteur

2024-03-19 14:51 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      <course-billing-infos v-if="company._id" :company="company" @refresh-company="refreshCompany" />
j'ai rajouté ._id dans le watch et created de coursebilllingInfos sinon ça pétait de le retirer ici

2024-03-19 15:00 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      <ni-select v-if="hasHoldingRole" caption="Structure" :model-value="selectedCompany._id"
done

2024-03-19 16:23 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +const getHoldingAbilities = role => roleBasedAccessControl[role].map(r => r.name);
c'est la même fonction ouais mais je trouvais que juste mettre getAbilities c'était pas forcément clair et getVendorOrHoldingAbilities un peu bizarre et je me dis que quand on va faire la suppression du code ERP, on va virer la contrainte filter sur getClientAbilities et du coup on homogénéisera à ce moment avec getAbilities, non ?

2024-03-20 08:28 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      await $store.dispatch('company/fetchCompany', { companyId });
Ici il y a un probleme de rafraichissement quand on est connecté ETQ holding admin, qu'on selectionne une structure , on edite le chargé de factu puis on change de structure. Quand on revient sur la premiere structure, le chargé de factu affiché est l'ancien

2024-03-20 08:29 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if (company.value._id) await $store.dispatch('company/fetchCompany', { companyId: company.value._id });
Oui dans le fond c'est pareil mais ca me semblait plus logique d'associer le role holding a `selectedCompany` mais ton argument me va

2024-03-20 08:31 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      await $store.dispatch('company/fetchCompany', { companyId });
Tu pourrais utiliser refreshCompany non ?

2024-03-20 08:34 UTC, manonpalin commented on src/core/helpers/ability.js
> +const getHoldingAbilities = role => roleBasedAccessControl[role].map(r => r.name);
hmm je ne suis pas certaine qu'on pense a faire cetet modif quanf on retirera le code ERP ! 

Ca me semble mieux de faire la modif ici, que penses-tu de `getInterfaceAbilities` ou `getRoleAbilities` ?

2024-03-20 08:47 UTC, ulysseferreira commented on src/core/helpers/ability.js
> +const getHoldingAbilities = role => roleBasedAccessControl[role].map(r => r.name);
done

2024-03-20 09:32 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +      await $store.dispatch('company/fetchCompany', { companyId });
done (j'ai fait un peu différemment on peut s'appeler pour en parler)

2024-03-20 14:14 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const setCompany = async (companyId) => {
Il manque un try / catch dans cette methode

2024-03-20 14:30 UTC, manonpalin commented
![Capture d’écran 2024-03-20 à 15 29 24](https://github.com/sophiemoustard/compani-webapp/assets/81675019/6d800bd8-24ab-4bae-91fe-8062a417c813)
L'affichage est coupé en 2

2024-03-20 14:35 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if ($store.state.company.company) {
Ce if + tout ce qu'il y a dedans me parait un peu compliqué et je me questionne sur la maintenabilité de ce bout de code :/ 

Est-ce que pour simplifier la comprehension il ne faudrait pas créer une variable qui stocke `$store.state.company.company` ?

2024-03-20 14:42 UTC, manonpalin commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          if (company.value._id) await $store.dispatch('company/fetchCompany', { companyId: company.value._id });
En fait en relisant une deuxieme fois, je me dis que selectedCompany est plus aproprié dans ce cas car ce qui nous interesse c'est de savoir si une valeur a ete selectionnée dans le selecteur ou non

2024-03-20 15:22 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const setCompany = async (companyId) => {
done

2024-03-20 17:49 UTC, sophiemoustard requested changes

2024-03-20 17:49 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          selectedCompany.value = {};
pourquoi `{}` et pas `null` ?

2024-03-20 17:49 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const company = computed(() => (hasHoldingRole.value ? selectedCompany.value : loggedUser.value.company));
que penses tu de nommer cette variable de manière un peu plus spécifique ? `displayedCompany` ou `currentCompany` par exemple

2024-03-21 08:19 UTC, sophiemoustard reviewed
cote vendeur, quand je vais sur la riche d'une formation et que je navigue en arriere, j'ai des erreurs en console
<img width="1440" alt="image" src="https://github.com/sophiemoustard/compani-webapp/assets/24521863/115b8f34-771e-4d17-98b0-44c70e7208c3">

2024-03-21 08:19 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +  <div v-if="company._id">
tu peux mettre le `if` directement sur le template du dessus non ? et ne pas avoir de div ici

2024-03-21 08:19 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +      return [companyBillsPayedByCompany, companyBillsPayedByOther, otherBillsPayedByCompany];
ici tu pourrais filtrer la liste pour ne garder que les tableaux qui ont des factures et eviter d'avoir a mettre le double `v-if="billList.length"` dans le template qu'en pense tu ?

2024-03-21 08:19 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    } = useCourseBilling(courseBillList);
sur une ligne

2024-03-21 08:19 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +            { ...omit(editedCoursePayment.value, ['_id', 'nature']) }
tu n'es pas obligé de mettre l'opérateur `...` ici ; omit renvoit deja un nouvel objet https://lodash.com/docs/4.17.15#omit

2024-03-21 08:19 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +      if (course.companies.find(comp => hasUserAccessToCompany(loggedUser.value, comp))) {
que penses de creer une methode `hasUserAccessToCoure` que tu pourrais réutiliser en dessous aussi ?

2024-03-21 08:19 UTC, sophiemoustard commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +        :options="companiesOptions" @update:model-value="setCompany($event)" clearable class="q-mt-xl" />
tu pourrais le mettre dans le composant `titleHeader` pour qu'il apparaissent en haut a droite comme les filtres sur les autres page (A facture, Balance client par exemple)

2024-03-21 09:02 UTC, ulysseferreira commented
> cote vendeur, quand je vais sur la riche d'une formation et que je navigue en arriere, j'ai des erreurs en console <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/24521863/315205337-115b8f34-771e-4d17-98b0-44c70e7208c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTE5NDAsIm5iZiI6MTcxMTAxMTY0MCwicGF0aCI6Ii8yNDUyMTg2My8zMTUyMDUzMzctMTE1YjhmMzQtNzcxZS00ZDE3LTk4YjAtNDRjNzBlNzIwOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NGY5M2YwNGUzNmY5OWQ0MTkwMTEyZTZiYmU4MTkxZjFmZjhlNWYzODhlNjIzNDU5NGQyNmQ3M2I3ZTM3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O7wwjsYigUzGEkEx9N6o2roPVlVFk4lcdhp9WSxTiEg">

tu as quelle erreur ? je n'en ai pas de mon côté et je n'en vois pas sur ton screen

2024-03-21 09:29 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +          selectedCompany.value = {};
done

2024-03-21 09:31 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +    const company = computed(() => (hasHoldingRole.value ? selectedCompany.value : loggedUser.value.company));
done

2024-03-21 09:34 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +  <div v-if="company._id">
ça pète si je fais ça, je suis pas sûr qu'on puisse mettre un v-if sur le tout premier template d'un composant, sinon le composant n'existe juste pas et c'est plus un v-if sur le composant qu'il faut mettre je pense

2024-03-21 09:38 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    } = useCourseBilling(courseBillList);
done

2024-03-21 09:39 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +            { ...omit(editedCoursePayment.value, ['_id', 'nature']) }
done

2024-03-21 09:42 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +      if (course.companies.find(comp => hasUserAccessToCompany(loggedUser.value, comp))) {
done

2024-03-21 09:57 UTC, ulysseferreira commented on src/modules/client/pages/ni/courses/BillingProfile.vue
> +        :options="companiesOptions" @update:model-value="setCompany($event)" clearable class="q-mt-xl" />
done

2024-03-21 14:16 UTC, manonpalin approved these changes

2024-03-21 15:39 UTC, sophiemoustard approved these changes

2024-03-21 15:39 UTC, sophiemoustard commented on src/modules/vendor/components/companies/ProfileBilling.vue
>      };
il y a beaucoup d'appels a GET /copmanies/_id qui partent au changement d'onglet Info > Factures
Je pense que ce `created` n'est pas necessaire car le rafraichissement de la structure est deja gerée par le `watch` dans `ProfileTabs` il me semble

2024-03-21 15:39 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    };
c'est en doublon avec le watcher juste au dessus ; je pense que cet appel n'est pas necessaire

2024-03-21 16:09 UTC, ulysseferreira commented on src/modules/vendor/components/companies/ProfileBilling.vue
>      };
done

2024-03-21 16:10 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    };
si je le retire, etq holding_admin si je vais sur le profil d'une formation et que je reviens, les factures et chargés de factu potentiels ne sont pas chargées

2024-03-22 07:56 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    };
hum il y a un truc a cresuer dans ce cas car les appels partent en double pour le rof donc c'est dommage

2024-03-22 08:24 UTC, sophiemoustard commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    };
Les comportements ne sont pas les même : 
ETQ ROF : 
- Quand on navigue de l'onglet infos a l'onglet factures d'une fiche structure, l'appel est déclenché par le `created` et le `watch` -> 2 appels
- Quand on arrive sur l'onglet facture depuis la fiche formation, l'appel n'est declenché que par le `watch` car `company` n'est pas definie quand on passe dans le `created` -> 1 appel

ETQ Admin Client : 
- Quand on arrive sur la page des factures, l'appel n'est declenché que par le `watch` car `company` n'est pas definie quand on passe dans le `created` -> 1 appel
- Quand on arrive sur l'onglet facture depuis la fiche formation, l'appel est déclenché par le `created` et le `watch` -> 2 appels

ETQ Admin Société mère : 
- Quand on arrive sur la page des factures, il n'y a pas de structure de selectionnée, donc pas de `company`, l'appel du `created` ne se delcenche pas  -> 0 appel ; 
    - quand on selectionne une structure, le `watch` se declenche -> 1 appel
- Quand on arrive sur l'onglet facture depuis la fiche formation, l'appel n'est declenché que par le `created` car `company` dans le store ne change pas et donc le `watch` n'est pas appelé -> 1 appel

est ce qu'il ne faudrait pas conditionner l'appel dans le created au role Admin Société mère ?

2024-03-22 09:07 UTC, ulysseferreira commented on src/core/components/courseBilling/CourseBillingInfos.vue
> +    };
done, je pense en effet qu'il n'y a pas d'autres solutions

2024-03-22 09:57 UTC, sophiemoustard approved these changes

2024-03-22 09:58 UTC, merged