COM-3774: add holding name in creation user select
sophiemoustard/compani-webapp pull request #2045
Opened 2024-09-04 09:42 UTC by ulysseferreira

- [x] J'ai vérifié la fonctionnalité sur mobile
- [ ] ~~J'ai ajouté une variable d'environnement~~
  - [ ] Si oui, J'ai précisé sur le [Doc de MES](https://www.notion.so/Pas-pas-Mise-en-staging-01755ac57d944b4cb0c189861428e5d2) et [Doc de MEP](https://www.notion.so/Pas-pas-Mise-en-prod-0f8e4879217d4c9e8e4d46d44211e0e3) les modifications faites

_Si tu as lu cette description, pense à réagir avec un :eye:_

2024-09-05 14:51 UTC, sophiemoustard requested changes

2024-09-05 14:51 UTC, sophiemoustard commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
pourquoi ce changement ? j'ai du mal a voir ce qui est faux dans prendre `course.value.companies`

2024-09-05 14:51 UTC, sophiemoustard commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
est s'il faut garder ton nouveau fonctionnement, je me demande si les options seront toujours bien trier comme on le veut ?

2024-09-06 08:18 UTC, ulysseferreira commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
on n'a pas les holdings dans course.value.companies ça oblie à faire des modifs dans le back dont on aurait besoin qu'à cet endroit alors qu'on peut récupérer ce qu'on veut grâce à d'autres variables qu'on a déjà

2024-09-06 08:19 UTC, ulysseferreira commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
qu'est-ce-que tu veux dire par triés comme on le veut ?

2024-09-07 08:00 UTC, sophiemoustard commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
un de mes commentaires ne s'est pas enregitré : j'aavis peur qu'en faisant ce on ait des structures en trop dans la liste : celles qui sont dans `getCurrentAndFutureCompanies` des apprenants mais pas dans les structures de la formation ; je viens de retester, c'est bon

2024-09-07 08:05 UTC, sophiemoustard commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
![image](https://github.com/user-attachments/assets/14ad8b6d-438d-413d-bd66-6c13bfe23d3a)
ce n'est pas trié par ordre alphabétique 
tu prends une ensemble de liste chacun triée par ordre alphabetique puis tu les concatènes en ne gardant que les valeurs uniques, mais rien ne te dis que la liste finale est bien triée...

2024-09-09 07:13 UTC, ulysseferreira commented on src/core/components/courses/TraineeContainer.vue
> +    const companyOptions = computed(() => uniqBy(Object.values(traineesCompanyOptions.value).flat(), 'value'));
corrigé

2024-09-09 07:28 UTC, sophiemoustard approved these changes

2024-09-09 07:28 UTC, merged